export const DISPLAY_CATEGORIES = [
    "llm",
    "image-generation",
    "image-editing",
    "video-generation",
    "video-editing",
    "coding",
    "voice-tts",
    "3d",
    "automation",
    "music",
    "presentation",
    "meeting-notes",
    "marketing",
    "writing",
    "education",
    "chatbot",
    "avatar",
    "web-builder",
    "game",
    "etc"
] as const;

export const CATEGORY_LABELS: Record<string, string> = {
    "llm": "LLM",
    "image-generation": "이미지 생성",
    "image-editing": "이미지 편집",
    "video-generation": "영상 생성",
    "video-editing": "영상 편집",
    "coding": "코딩",
    "voice-tts": "목소리",
    "3d": "3D",
    "automation": "자동화",
    "music": "음악",
    "presentation": "프레젠테이션",
    "meeting-notes": "회의록",
    "marketing": "마케팅",
    "writing": "글쓰기",
    "education": "교육/연구",
    "chatbot": "챗봇",
    "avatar": "아바타",
    "web-builder": "웹빌더",
    "game": "게임",
    "etc": "기타"
};

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
    "llm": "AI의 표준, 가장 무난하고 강력한 대화형 모델",
    "image-generation": "텍스트로 예술적인 이미지를 만들어내는 도구",
    "image-editing": "사진의 배경 제거, 화질 개선 등 마법 같은 편집",
    "video-generation": "상상 속 장면을 현실적인 비디오로 구현",
    "video-editing": "자동 자막, 컷 편집 등 영상 제작의 효율화",
    "coding": "개발자의 생산성을 획기적으로 높여주는 코딩 비서",
    "voice-tts": "텍스트를 가장 자연스러운 사람의 목소리로 변환",
    "3d": "텍스트나 이미지로 3D 모델과 에셋을 즉시 생성",
    "automation": "복잡한 반복 업무를 자동으로 처리하는 워크플로우",
    "music": "가사만 있으면 작곡부터 노래까지 완성하는 AI 음악",
    "presentation": "주제만 주면 디자인된 PPT와 발표 자료 완성",
    "meeting-notes": "회의 내용을 녹음하고 요약해주는 스마트한 비서",
    "marketing": "카피라이팅부터 SEO까지 마케팅의 모든 것",
    "writing": "블로그, 소설, 이메일 등 모든 글쓰기를 돕는 도구",
    "education": "논문 요약, 언어 학습 등 배움을 돕는 AI 튜터",
    "chatbot": "고객 응대부터 개인 비서까지, 나만의 챗봇 만들기",
    "avatar": "텍스트를 말하는 가상 인간 아바타 영상 제작",
    "web-builder": "디자인하듯 그리면 코드로 변환되는 웹사이트 제작",
    "game": "게임 에셋 생성부터 NPC 대화까지 게임 개발 혁신",
    "etc": "번역, 엑셀, PDF 분석 등 유용한 생산성 도구 모음"
};
