// AI 정보 사이트 큐레이션 — 영어 오버레이(/en/ai-news 전용).
// URL·배지·구조는 aiNewsData.ts를 재사용하고, 카테고리 라벨/설명과 사이트 설명만 영어로 덮어씀.

export const AI_NEWS_CATEGORIES_EN: Record<string, { label: string; desc: string }> = {
  "kr-news": { label: "Korean AI News", desc: "The Korean-language outlets developers and operators in Korea read most" },
  "kr-community": { label: "Korean Communities & Blogs", desc: "Where Korean developers and makers gather to share what they learn" },
  news: { label: "Global News & Media", desc: "Outlets that cover AI industry and product moves fastest" },
  community: { label: "Global Communities", desc: "Where real users argue, experiment and troubleshoot" },
  newsletter: { label: "Newsletters", desc: "Daily and weekly AI digests that keep only what matters" },
  youtube: { label: "YouTube & Podcasts", desc: "AI trends and explainers in video and audio" },
  leaderboard: { label: "Leaderboards & Benchmarks", desc: "Compare model performance on objective numbers" },
  tools: { label: "Tool Discovery", desc: "Hubs for finding and trying new AI tools and models" },
  research: { label: "Research & Papers", desc: "Track primary research and the newest papers yourself" },
  labs: { label: "Official Labs & Company Blogs", desc: "First-party announcements straight from the major AI labs" },
  learn: { label: "Learning & Tutorials", desc: "Resources to learn AI, from fundamentals to production" },
};

// 사이트명 → 영어 설명
export const AI_SITE_DESC_EN: Record<string, string> = {
  // 한국 AI 소식
  "GeekNews": "Korea's must-read tech news aggregator, very active on AI and startups",
  "AI타임스": "Korea's leading AI trade publication — industry, policy and research",
  "인공지능신문": "Korean-language news on the AI industry and new services",
  "요즘IT": "IT and AI magazine written from a practitioner's point of view",
  "바이라인네트워크": "In-depth reporting on tech and startups",
  "더밀크": "AI and tech analysis reported from Silicon Valley",
  "ZDNet Korea": "IT and AI industry news",
  "AI 포스트": "Korean-language news on generative AI and new services",
  // 한국 커뮤니티·블로그
  "GPTers": "Korea's largest community for putting generative AI to work",
  "디스콰이엇": "Product community for makers and startups",
  "OKKY": "Q&A and community for developers",
  "velog": "Korean developer tech blogs (AI tag)",
  "모두의연구소": "Community for AI research and education",
  // 글로벌 뉴스·미디어
  "TechCrunch AI": "Breaking news on startups, launches and funding",
  "The Verge AI": "Consumer-friendly AI news and reviews",
  "VentureBeat AI": "Focused on enterprise AI and infrastructure",
  "MIT Tech Review": "Deep analysis and outlook on AI",
  "The Decoder": "Daily news dedicated to AI",
  "Ars Technica AI": "AI coverage with real technical depth",
  "WIRED AI": "AI stories through a cultural and social lens",
  "The Information": "High-end insider reporting on tech (paid)",
  "Semafor Tech": "Newsletter-style analysis of tech and AI",
  // 글로벌 커뮤니티
  "Hacker News": "Home of tech and startup discussion — AI posts trend constantly",
  "r/LocalLLaMA": "Hands-on community for local LLMs and open models",
  "r/MachineLearning": "Subreddit for research and paper discussion",
  "r/OpenAI": "Discussion of ChatGPT and OpenAI",
  "r/ChatGPT": "Huge subreddit for ChatGPT tips, memes and debate",
  "r/StableDiffusion": "Practical talk on image generation models",
  "r/singularity": "Discussion of AGI and where technology is heading",
  "Lobsters": "Curated, tech-focused link community",
  // 뉴스레터
  "TLDR AI": "Five-minute daily roundup of what matters in AI",
  "The Batch": "Andrew Ng's weekly AI digest",
  "Ben's Bites": "Friendly daily AI newsletter",
  "The Rundown AI": "Daily issue focused on tools and how to use them",
  "The Neuron": "Easy-to-read daily AI briefing",
  "Import AI": "Jack Clark's weekly deep analysis",
  "Last Week in AI": "Weekly wrap of research and industry news",
  "One Useful Thing": "Ethan Mollick's practical essays on using AI",
  // 유튜브·팟캐스트
  "Two Minute Papers": "The latest papers explained in two-minute videos",
  "AI Explained": "Balanced, in-depth AI explainers",
  "Lex Fridman Podcast": "Long-form interviews with leading AI figures",
  "Yannic Kilcher": "Paper reviews and technical deep dives",
  "Matthew Berman": "Hands-on reviews of new models and tools",
  "Latent Space": "Podcast and newsletter for AI engineers",
  "TWIML AI Podcast": "Interviews on applied machine learning and research",
  // 리더보드·벤치마크
  "LMArena": "LLM rankings from human votes (formerly Chatbot Arena)",
  "Artificial Analysis": "Compare intelligence, speed and price side by side",
  "Open LLM Leaderboard": "Benchmark rankings for open models",
  "OpenRouter Rankings": "Model and app rankings based on real usage",
  "LiveBench": "LLM benchmark designed to resist contamination",
  "Aider Leaderboard": "Leaderboard for coding performance",
  "SWE-bench": "Benchmark on solving real GitHub issues",
  "Vellum Leaderboard": "Model specs and pricing at a glance",
  // 도구 발견·디렉토리
  "There's An AI For That": "Large directory of AI tools organised by use case",
  "Product Hunt AI": "New AI product launches and trends",
  "Future Tools": "Tool collection curated by Matt Wolfe",
  "Futurepedia": "Large-scale AI tool directory",
  "Toolify": "Tool directory that also shows traffic rankings",
  "Hugging Face": "The hub for open models, datasets and Spaces",
  "Replicate": "Run models straight from an API",
  "Civitai": "Sharing hub for image models and LoRAs",
  // 연구·논문
  "arXiv (cs.AI)": "Newest AI preprints",
  "HF Papers": "Daily curation of the papers people are talking about",
  "Papers with Code": "Papers linked to implementations and benchmarks",
  "alphaXiv": "Discussion and commentary on arXiv papers",
  "Semantic Scholar": "AI-powered academic search",
  "Connected Papers": "Visualise how papers cite one another",
  "Google Scholar": "Unified search across academic papers",
  // 공식 랩·기업 블로그
  "OpenAI News": "Official announcements and research from OpenAI",
  "Anthropic News": "Official announcements and research from Anthropic (Claude)",
  "Google DeepMind": "DeepMind's research blog",
  "Google Research": "Google's research blog",
  "Meta AI": "Meta AI announcements, including Llama",
  "Microsoft Research": "Microsoft's research blog",
  "Mistral AI": "Mistral model announcements",
  "Hugging Face Blog": "Practical writing on open-source AI",
  "NVIDIA Blog": "News on GPUs and AI infrastructure",
  "xAI": "xAI announcements, including Grok",
  // 학습·튜토리얼
  "DeepLearning.AI": "Andrew Ng's hub for AI courses",
  "fast.ai": "Free, practice-first deep learning course",
  "Hugging Face Learn": "Free courses on NLP, LLMs and agents",
  "Kaggle": "Hands-on data and ML practice with competitions",
  "ML Crash Course": "Google's introduction to machine learning",
  "Prompt Engineering Guide": "Comprehensive guide to prompting techniques",
  "Learn Prompting": "Free site for learning prompt engineering",
};
