import { AiTool } from "@/types/content";

/**
 * AI Tools 데이터 목록
 * 
 * @description AI Tools 페이지에 표시될 도구 데이터입니다.
 * 각 항목은 AiTool 타입을 따르며, 카테고리별로 분류되어 있습니다.
 */
export const AI_TOOLS_DATA: AiTool[] = [
  // =====================================================================================
  // 1. LLM (대화형/언어모델)
  // =====================================================================================
  {
    id: "llm-01",
    name: "ChatGPT",
    category: "llm",
    description: "OpenAI가 개발한 가장 대중적인 대화형 AI로, GPT-4o 모델을 기반으로 텍스트 생성, 코딩, 번역, 분석 등 다양한 작업을 수행합니다. 직관적인 인터페이스와 강력한 성능으로 전 세계 수억 명이 사용하고 있습니다.",
    summary: "대화형 AI의 표준, GPT-4o 탑재",
    website: "https://chat.openai.com",
    releaseDate: "2022.11",
    pricing: "Free / $20 mo",
    tags: ["Chat", "Coding", "Writing"],
    thumbnail: "https://logo.clearbit.com/openai.com",
    rating: 0,
    ratingCount: 0,
    userRatings: [],
    comments: []
  },
  {
    id: "llm-02", name: "Claude 3", category: "llm",
    description: "Anthropic이 개발한 인간다운 대화형 AI로, 특히 긴 문서 분석과 정확한 문맥 이해에 뛰어납니다. 안전성과 정직성을 중시하는 설계 철학으로 신뢰할 수 있는 AI 어시스턴트 역할을 합니다.",
    summary: "가장 인간다운 문맥 이해력을 가진 AI",
    website: "https://claude.ai", releaseDate: "2024.03", pricing: "Free / $20 mo", tags: ["Writing", "Analysis", "Long-context"],
    thumbnail: "https://logo.clearbit.com/anthropic.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  {
    id: "llm-03", name: "Gemini", category: "llm",
    description: "Google이 개발한 멀티모달 AI 모델로, 텍스트, 이미지, 음성을 동시에 처리할 수 있습니다. Gmail, Google Docs, YouTube 등 구글 서비스와 완벽하게 통합되어 생산성을 극대화합니다.",
    summary: "구글 생태계와 완벽하게 연동되는 멀티모달",
    website: "https://gemini.google.com", releaseDate: "2023.12", pricing: "Free / $20 mo", tags: ["Multimodal", "Google"],
    thumbnail: "https://logo.clearbit.com/google.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "llm-04", name: "Perplexity", category: "llm", summary: "실시간 검색 기반 답변 엔진.", description: "실시간 웹 검색과 AI 답변을 결합한 혁신적인 검색 엔진입니다. 모든 답변에 출처를 명시하여 신뢰성을 보장하며, 최신 정보를 빠르게 찾아 요약해줍니다.", releaseDate: "2022.08", website: "https://perplexity.ai", pricing: "Free / $20 mo", tags: ["Search", "Citations"], thumbnail: "https://logo.clearbit.com/perplexity.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-05", name: "Mistral", category: "llm", summary: "유럽 최고의 오픈소스 모델.", description: "프랑스 Mistral AI가 개발한 고성능 오픈소스 LLM으로, 작은 모델 크기 대비 뛰어난 성능을 보여줍니다. 상업적 이용이 자유롭고 API와 로컬 배포를 모두 지원합니다.", releaseDate: "2023.09", website: "https://mistral.ai", pricing: "Open Source", tags: ["Open Source", "Efficient"], thumbnail: "https://logo.clearbit.com/mistral.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-06", name: "Llama 3", category: "llm", summary: "Meta의 강력한 오픈소스 모델.", description: "Meta가 공개한 최신 오픈소스 언어 모델로, 8B부터 405B까지 다양한 크기를 제공합니다. 개인 및 상업적 용도로 자유롭게 사용 가능하며 로컬 구동이 가능합니다.", releaseDate: "2024.04", website: "https://llama.meta.com", pricing: "Open Source", tags: ["Meta", "Local LLM"], thumbnail: "https://logo.clearbit.com/meta.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-07", name: "Grok", category: "llm", summary: "xAI의 위트 있는 AI.", description: "엘론 머스크의 xAI가 개발한 AI로, X(트위터)의 실시간 데이터에 접근할 수 있어 최신 트렌드와 뉴스를 반영합니다. 유머러스하고 솔직한 답변 스타일이 특징입니다.", releaseDate: "2023.11", website: "https://x.ai", pricing: "Paid (X Premium)", tags: ["Real-time", "Humor"], thumbnail: "https://logo.clearbit.com/x.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-08", name: "Cohere", category: "llm", summary: "기업용 RAG 특화 모델.", description: "기업의 내부 데이터베이스와 문서를 연결하여 정확한 답변을 제공하는 RAG(검색 증강 생성) 특화 모델입니다. 데이터 프라이버시와 보안을 중시하는 엔터프라이즈 솔루션입니다.", releaseDate: "2022.06", website: "https://cohere.com", pricing: "API Pricing", tags: ["Enterprise", "RAG"], thumbnail: "https://logo.clearbit.com/cohere.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-09", name: "Pi", category: "llm", summary: "감성적인 대화 파트너.", description: "Inflection AI가 개발한 감성 지능이 뛰어난 AI로, 사용자의 감정 상태를 파악하고 공감하는 대화를 이어갑니다. 일상적인 대화와 정서적 지원에 최적화된 개인 비서입니다.", releaseDate: "2023.05", website: "https://pi.ai", pricing: "Free", tags: ["Emotional", "Chat"], thumbnail: "https://logo.clearbit.com/pi.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-10", name: "HyperCLOVA X", category: "llm", summary: "한국어에 가장 강한 AI.", description: "네이버가 개발한 한국어 특화 거대언어모델로, 한국어의 뉘앙스와 문화적 맥락을 깊이 이해합니다. 네이버 서비스 전반에 통합되어 검색, 쇼핑, 지식백과 등에서 활용됩니다.", releaseDate: "2023.08", website: "https://clova.ai", pricing: "Enterprise", tags: ["Korean", "Naver"], thumbnail: "https://logo.clearbit.com/navercorp.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-11", name: "Falcon 180B", category: "llm", summary: "가장 강력한 오픈소스 모델 중 하나.", description: "UAE 기술혁신연구소(TII)가 개발한 1800억 파라미터 규모의 초대형 오픈소스 모델입니다. 상업적 이용이 자유롭고 GPT-3.5 수준의 성능을 보여줍니다.", website: "https://falconllm.tii.ae", releaseDate: "2023.09", pricing: "Open Source", tags: ["Open Source", "High Perf"], thumbnail: "https://logo.clearbit.com/tii.ae", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-12", name: "Qwen", category: "llm", summary: "Alibaba의 고성능 LLM.", description: "알리바바가 개발한 다국어 오픈소스 모델로, 중국어와 영어를 비롯한 다양한 언어를 지원합니다. 수학 문제 해결과 코드 생성 능력이 특히 뛰어납니다.", website: "https://qwenlm.github.io", releaseDate: "2023.08", pricing: "Open Source", tags: ["Alibaba", "Coding"], thumbnail: "https://logo.clearbit.com/alibaba.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-13", name: "Yi", category: "llm", summary: "01.AI의 강력한 이중언어 모델.", description: "01.AI가 개발한 영어와 중국어에 특화된 고성능 모델입니다. 최대 200K 토큰의 긴 문맥을 처리할 수 있어 긴 문서 분석과 대화에 적합합니다.", website: "https://01.ai", releaseDate: "2023.11", pricing: "Open Source", tags: ["Bilingual", "Long Context"], thumbnail: "https://logo.clearbit.com/01.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-14", name: "DeepSeek", category: "llm", summary: "코딩에 강한 오픈소스 LLM.", description: "코딩과 수학 문제 해결에 특화된 중국산 오픈소스 모델입니다. GitHub Copilot 수준의 코드 생성 능력을 보여주며, 복잡한 수학 문제도 정확하게 풀어냅니다.", website: "https://deepseek.com", releaseDate: "2023.11", pricing: "Open Source", tags: ["Coding", "Math"], thumbnail: "https://logo.clearbit.com/deepseek.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-15", name: "Solar", category: "llm", summary: "업스테이지의 한국어 특화 LLM.", description: "업스테이지가 개발한 한국어와 영어에 최적화된 고성능 모델입니다. 작은 모델 크기 대비 뛰어난 성능을 자랑하며, API를 통해 쉽게 통합할 수 있습니다.", website: "https://upstage.ai", releaseDate: "2023.12", pricing: "API", tags: ["Korean", "Efficient"], thumbnail: "https://logo.clearbit.com/upstage.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-16", name: "ChatGLM", category: "llm", summary: "칭화대의 다국어 대화 모델.", description: "칭화대학이 개발한 중국어와 영어 대화에 특화된 경량화 모델입니다. 6B 파라미터로 작은 크기임에도 뛰어난 성능을 보이며, 개인 PC에서도 구동 가능합니다.", website: "https://chatglm.cn", releaseDate: "2023", pricing: "Open Source", tags: ["Bilingual", "Local"], thumbnail: "https://logo.clearbit.com/tsinghua.edu.cn", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-17", name: "Vicuna", category: "llm", summary: "GPT-4 수준의 오픈소스 챗봇.", description: "UC Berkeley의 LMSYS가 개발한 Llama 기반 파인튜닝 모델로, GPT-4의 90% 이상 성능을 보여줍니다. 대화형 챗봇 구축에 최적화된 오픈소스 솔루션입니다.", website: "https://lmsys.org", releaseDate: "2023.03", pricing: "Open Source", tags: ["Chat", "Fine-tuned"], thumbnail: "https://logo.clearbit.com/lmsys.org", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-18", name: "WizardLM", category: "llm", summary: "복잡한 지시사항을 잘 따르는 AI.", description: "Microsoft가 개발한 Evol-Instruct 방식으로 훈련된 모델로, 복잡하고 다단계 지시사항을 정확하게 이해하고 수행합니다. 코드 생성과 문제 해결에 특히 강점이 있습니다.", website: "https://wizardlm.github.io", releaseDate: "2023.04", pricing: "Open Source", tags: ["Instruction", "Complex"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-19", name: "Orca 2", category: "llm", summary: "Microsoft의 추론 강화 모델.", description: "Microsoft가 개발한 소형 모델로, 7B와 13B 크기임에도 복잡한 추론 작업을 잘 수행합니다. 단계별 사고 과정을 학습하여 논리적 문제 해결 능력이 뛰어납니다.", website: "https://microsoft.com", releaseDate: "2023.11", pricing: "Open Source", tags: ["Reasoning", "Small"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-20", name: "Gemma", category: "llm", summary: "Google의 경량화 오픈 모델.", description: "Google이 Gemini 기술을 기반으로 개발한 오픈소스 모델로, 2B와 7B 두 가지 크기를 제공합니다. 작은 크기 대비 뛰어난 성능으로 개인 개발자와 연구자들에게 인기입니다.", website: "https://ai.google.dev/gemma", releaseDate: "2024.02", pricing: "Open Source", tags: ["Google", "Lightweight"], thumbnail: "https://logo.clearbit.com/google.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 2. Image (이미지 생성) - 총 20개
  // =====================================================================================
  {
    id: "img-01", name: "Midjourney", category: "image",
    summary: "가장 예술적인 이미지 생성기.",
    description: "Discord 봇 형태로 동작하는 이미지 생성 AI로, 현존하는 AI 중 가장 뛰어난 예술적 화질과 창의성을 자랑합니다. 미술, 일러스트, 컨셉 아트 제작에 최적화되어 있습니다.",
    releaseDate: "2022.07", website: "https://midjourney.com", pricing: "$10~$120 mo", tags: ["High Quality", "Art"],
    thumbnail: "https://logo.clearbit.com/midjourney.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "img-02", name: "Stable Diffusion", category: "image", summary: "로컬 설치 가능한 오픈소스.", description: "Stability AI가 개발한 오픈소스 이미지 생성 모델로, PC에 직접 설치하여 무료로 무제한 이미지를 생성할 수 있습니다. ControlNet, LoRA 등 다양한 확장 기능을 지원합니다.", releaseDate: "2022.08", website: "https://stability.ai", pricing: "Free (Open Source)", tags: ["Local", "ControlNet"], thumbnail: "https://logo.clearbit.com/stability.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-03", name: "Leonardo.ai", category: "image", summary: "게임 에셋과 아트에 특화.", description: "게임 개발자와 아티스트를 위한 이미지 생성 플랫폼으로, 다양한 커스텀 모델을 제공합니다. 게임 아이템, 캐릭터, 배경 등 게임 에셋 제작에 최적화되어 있으며 직관적인 UI를 제공합니다.", releaseDate: "2022.12", website: "https://leonardo.ai", pricing: "Free / Paid", tags: ["Game Asset", "Easy UI"], thumbnail: "https://logo.clearbit.com/leonardo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-04", name: "DALL-E 3", category: "image", summary: "ChatGPT 안에서 그리는 그림.", description: "OpenAI가 개발한 이미지 생성 AI로, ChatGPT Plus 구독 시 사용할 수 있습니다. 프롬프트를 정확하게 이해하며 이미지 내 텍스트 렌더링 능력이 뛰어나 로고나 포스터 제작에 적합합니다.", releaseDate: "2023.10", website: "https://openai.com/dall-e-3", pricing: "Included in ChatGPT Plus", tags: ["Simple", "Text Rendering"], thumbnail: "https://logo.clearbit.com/openai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-05", name: "Adobe Firefly", category: "image", summary: "상업적 사용이 안전한 AI.", description: "Adobe가 개발한 상업적 이용이 안전한 이미지 생성 AI로, Adobe Stock 이미지로만 학습되어 저작권 문제가 없습니다. Photoshop, Illustrator 등 어도비 제품군과 완벽하게 통합됩니다.", releaseDate: "2023.03", website: "https://firefly.adobe.com", pricing: "Free / Credits", tags: ["Commercial", "Photoshop"], thumbnail: "https://logo.clearbit.com/adobe.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-06", name: "Ideogram", category: "image", summary: "텍스트 타이포그래피 최강자.", description: "이미지 내에 정확한 글자를 삽입하는 능력이 매우 뛰어납니다.", releaseDate: "2023.08", website: "https://ideogram.ai", pricing: "Free / Paid", tags: ["Typography", "Logo"], thumbnail: "https://logo.clearbit.com/ideogram.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-07", name: "Krea AI", category: "image", summary: "실시간 드로잉 & 업스케일.", description: "그리는 즉시 AI가 이미지를 완성해주는 실시간 기능을 제공합니다.", releaseDate: "2023.11", website: "https://krea.ai", pricing: "Free / Paid", tags: ["Real-time", "Upscale"], thumbnail: "https://logo.clearbit.com/krea.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-08", name: "Magnific AI", category: "image", summary: "이미지 디테일 업스케일러.", description: "저화질 이미지를 상상력을 더해 초고화질로 변환해줍니다.", releaseDate: "2023.12", website: "https://magnific.ai", pricing: "Paid", tags: ["Upscale", "Detail"], thumbnail: "https://logo.clearbit.com/magnific.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-09", name: "Playground AI", category: "image", summary: "사용하기 쉬운 웹 생성기.", description: "필터 기능이 강력하고 커뮤니티 기능이 잘 되어 있습니다.", releaseDate: "2022.10", website: "https://playgroundai.com", pricing: "Free / Paid", tags: ["Web-based", "Filters"], thumbnail: "https://logo.clearbit.com/playground.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-10", name: "Recraft", category: "image", summary: "벡터 이미지 생성 특화.", description: "SVG 포맷으로 저장 가능한 벡터 그래픽과 아이콘을 생성합니다.", releaseDate: "2023.05", website: "https://recraft.ai", pricing: "Free / Paid", tags: ["Vector", "Icon"], thumbnail: "https://logo.clearbit.com/recraft.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-11", name: "Bing Image Creator", category: "image", summary: "DALL-E 3 기반 무료 생성기.", description: "MS 계정만 있으면 무료로 고품질 이미지를 생성할 수 있습니다.", website: "https://bing.com/images/create", releaseDate: "2023.03", pricing: "Free", tags: ["Microsoft", "Free"], thumbnail: "https://logo.clearbit.com/bing.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-12", name: "Clipdrop", category: "image", summary: "이미지 편집 및 생성 도구 모음.", description: "배경 제거, 조명 조절 등 다양한 AI 편집 도구를 제공합니다.", website: "https://clipdrop.co", releaseDate: "2020.07", pricing: "Free / Paid", tags: ["Editing", "Tools"], thumbnail: "https://logo.clearbit.com/clipdrop.co", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-13", name: "NightCafe", category: "image", summary: "커뮤니티 중심의 아트 생성기.", description: "다양한 알고리즘을 지원하며 일일 무료 크레딧을 제공합니다.", website: "https://creator.nightcafe.studio", releaseDate: "2019.11", pricing: "Free / Paid", tags: ["Community", "Art"], thumbnail: "https://logo.clearbit.com/nightcafe.studio", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-14", name: "Artbreeder", category: "image", summary: "이미지 합성 및 유전자 조작.", description: "여러 이미지를 섞어 새로운 스타일을 만들어내는 독특한 툴입니다.", website: "https://artbreeder.com", releaseDate: "2018", pricing: "Free / Paid", tags: ["Mixing", "Portraits"], thumbnail: "https://logo.clearbit.com/artbreeder.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-15", name: "Civitai", category: "image", summary: "Stable Diffusion 모델 공유 플랫폼.", description: "전 세계 유저들이 만든 다양한 SD 모델과 로라를 공유하고 실행합니다.", website: "https://civitai.com", releaseDate: "2022.11", pricing: "Free", tags: ["Models", "Community"], thumbnail: "https://logo.clearbit.com/civitai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-16", name: "SeaArt", category: "image", summary: "강력한 웹 기반 SD 툴.", description: "설치 없이 Stable Diffusion의 강력한 기능들을 웹에서 사용합니다.", website: "https://seaart.ai", releaseDate: "2023.05", pricing: "Free / Paid", tags: ["Web SD", "Free"], thumbnail: "https://logo.clearbit.com/seaart.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-17", name: "Tensor.art", category: "image", summary: "무료로 모델 실행 및 생성.", description: "다양한 모델을 무료로 실행해볼 수 있는 온라인 플랫폼입니다.", website: "https://tensor.art", releaseDate: "2023.06", pricing: "Free / Paid", tags: ["Models", "Generation"], thumbnail: "https://logo.clearbit.com/tensor.art", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-18", name: "Stockimg.ai", category: "image", summary: "스톡 이미지 생성 특화.", description: "로고, 책 표지, 포스터 등 목적에 맞는 스톡 이미지를 생성합니다.", website: "https://stockimg.ai", releaseDate: "2022.09", pricing: "Free / Paid", tags: ["Stock", "Design"], thumbnail: "https://logo.clearbit.com/stockimg.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-19", name: "Kaiber", category: "image", summary: "애니메이션 스타일 생성.", description: "이미지나 영상을 몽환적인 애니메이션 스타일로 변환합니다.", website: "https://kaiber.ai", releaseDate: "2023", pricing: "Paid", tags: ["Animation", "Style"], thumbnail: "https://logo.clearbit.com/kaiber.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-20", name: "Getimg.ai", category: "image", summary: "올인원 이미지 생성 및 편집.", description: "생성, 인페인팅, 아웃페인팅 등 다양한 기능을 한곳에서 제공합니다.", website: "https://getimg.ai", releaseDate: "2022", pricing: "Free / Paid", tags: ["Editor", "Suite"], thumbnail: "https://logo.clearbit.com/getimg.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 3. Video (영상 생성) - 총 20개
  {
    id: "vid-01", name: "Runway", category: "video",
    summary: "영상 생성 AI의 선두주자.",
    description: "텍스트 투 비디오, 모션 브러쉬 등 다양한 제어 기능을 제공합니다.",
    releaseDate: "2023.06", website: "https://runwayml.com", pricing: "Free Trial / Paid", tags: ["Gen-2", "Motion Brush"],
    thumbnail: "https://logo.clearbit.com/runwayml.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "vid-02", name: "Pika", category: "video", summary: "애니메이션에 강한 생성기.", description: "누구나 쉽게 사용하는 영상 생성.", website: "https://pika.art", releaseDate: "2023.12", pricing: "Free / Paid", tags: ["Animation", "Easy"], thumbnail: "https://logo.clearbit.com/pika.art", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-03", name: "Sora", category: "video", summary: "OpenAI의 혁명적 비디오 모델.", description: "최대 1분 길이의 고해상도 영상을 물리 법칙에 맞게 생성합니다. (현재 제한적 공개)", releaseDate: "2024.02", pricing: "Unreleased", tags: ["Realistic", "OpenAI"], thumbnail: "https://logo.clearbit.com/openai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-04", name: "Luma Dream Machine", category: "video", summary: "고퀄리티 무료 영상 생성.", description: "빠른 생성 속도와 높은 퀄리티를 무료로 체험할 수 있습니다.", releaseDate: "2024.06", website: "https://lumalabs.ai", pricing: "Free / Paid", tags: ["High Quality", "Fast"], thumbnail: "https://logo.clearbit.com/lumalabs.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-05", name: "Kling", category: "video", summary: "중국의 고성능 비디오 모델.", description: "Sora에 버금가는 긴 영상 생성 능력과 자연스러운 움직임을 보여줍니다.", releaseDate: "2024.06", website: "https://kling.kuaishou.com", pricing: "Free / Paid", tags: ["Long Video", "Realistic"], thumbnail: "https://logo.clearbit.com/kuaishou.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-06", name: "HeyGen", category: "video", summary: "AI 아바타 영상 제작.", description: "텍스트만 입력하면 실제 사람이 말하는 듯한 영상을 만들어줍니다.", releaseDate: "2022.09", website: "https://heygen.com", pricing: "Paid", tags: ["Avatar", "Marketing"], thumbnail: "https://logo.clearbit.com/heygen.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-07", name: "Synthesia", category: "video", summary: "기업 교육용 AI 아바타.", description: "다국어 지원 및 기업 교육, 프레젠테이션 영상 제작에 최적화되어 있습니다.", releaseDate: "2020.10", website: "https://synthesia.io", pricing: "Paid", tags: ["Business", "Avatar"], thumbnail: "https://logo.clearbit.com/synthesia.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-08", name: "Kaiber", category: "video", summary: "스타일리시한 영상 변환.", description: "기존 영상을 애니메이션이나 특정 스타일로 변환하는 데 특화되어 있습니다.", releaseDate: "2023.01", website: "https://kaiber.ai", pricing: "Paid", tags: ["Style Transfer", "Music Video"], thumbnail: "https://logo.clearbit.com/kaiber.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-09", name: "Leonardo Motion", category: "video", summary: "이미지를 영상으로.", description: "레오나르도 AI에서 생성한 이미지에 자연스러운 움직임을 부여합니다.", releaseDate: "2023.12", website: "https://leonardo.ai", pricing: "Credits", tags: ["Image-to-Video"], thumbnail: "https://logo.clearbit.com/leonardo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-10", name: "Topaz Video AI", category: "video", summary: "AI 영상 업스케일링.", description: "저화질 영상을 고화질로 복원하고 프레임 속도를 부드럽게 만듭니다.", releaseDate: "2020.05", website: "https://topazlabs.com", pricing: "One-time", tags: ["Upscale", "Restoration"], thumbnail: "https://logo.clearbit.com/topazlabs.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-11", name: "Hailuo AI", category: "video", summary: "MiniMax의 고성능 비디오 생성 AI.", description: "텍스트를 고품질의 비디오로 변환해주는 MiniMax사의 최신 비디오 생성 모델입니다.", releaseDate: "2024.09", website: "https://hailuoai.com", pricing: "Free / Paid", tags: ["Video", "MiniMax", "High Quality"], thumbnail: "https://logo.clearbit.com/hailuoai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-12", name: "Veed.io", category: "video", summary: "AI 기반 온라인 영상 편집기.", description: "자동 자막, 컷 편집 등 AI 기능을 갖춘 웹 기반 에디터입니다.", website: "https://veed.io", releaseDate: "2018", pricing: "Free / Paid", tags: ["Editing", "Subtitles"], thumbnail: "https://logo.clearbit.com/veed.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-13", name: "InVideo", category: "video", summary: "텍스트로 비디오 만들기.", description: "스크립트만 입력하면 스톡 영상을 조합해 비디오를 완성해줍니다.", website: "https://invideo.io", releaseDate: "2017", pricing: "Free / Paid", tags: ["Marketing", "Text-to-Video"], thumbnail: "https://logo.clearbit.com/invideo.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-14", name: "Fliki", category: "video", summary: "텍스트를 비디오와 음성으로.", description: "블로그 글이나 트윗을 영상으로 빠르게 변환해주는 툴입니다.", website: "https://fliki.ai", releaseDate: "2022", pricing: "Free / Paid", tags: ["Blog-to-Video", "Social"], thumbnail: "https://logo.clearbit.com/fliki.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-15", name: "Pictory", category: "video", summary: "긴 영상을 짧게 요약.", description: "웨비나나 팟캐스트 녹화본을 분석해 하이라이트 영상으로 만듭니다.", website: "https://pictory.ai", releaseDate: "2019", pricing: "Paid", tags: ["Summary", "Shorts"], thumbnail: "https://logo.clearbit.com/pictory.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-16", name: "Steve.ai", category: "video", summary: "애니메이션 비디오 생성.", description: "스크립트를 입력하면 애니메이션이나 실사 스타일의 비디오를 제작합니다.", website: "https://steve.ai", releaseDate: "2021", pricing: "Free / Paid", tags: ["Animation", "Marketing"], thumbnail: "https://logo.clearbit.com/steve.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-17", name: "Elai.io", category: "video", summary: "PPT로 AI 영상 만들기.", description: "프레젠테이션 파일을 업로드하면 AI 아바타가 설명하는 영상으로 변환합니다.", website: "https://elai.io", releaseDate: "2021", pricing: "Paid", tags: ["Presentation", "Avatar"], thumbnail: "https://logo.clearbit.com/elai.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-18", name: "Colossyan", category: "video", summary: "학습용 AI 비디오 제작.", description: "기업 교육 및 온보딩 영상 제작에 최적화된 아바타 툴입니다.", website: "https://colossyan.com", releaseDate: "2021", pricing: "Paid", tags: ["Education", "Corporate"], thumbnail: "https://logo.clearbit.com/colossyan.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-19", name: "D-ID", category: "video", summary: "사진을 말하게 만들기.", description: "정지된 인물 사진에 대사를 입력하면 입 모양을 움직여 말하게 합니다.", website: "https://d-id.com", releaseDate: "2017", pricing: "Free Trial / Paid", tags: ["Animation", "Photo"], thumbnail: "https://logo.clearbit.com/d-id.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-20", name: "Wondershare Filmora", category: "video", summary: "AI 기능이 탑재된 편집기.", description: "초보자도 쉽게 쓸 수 있는 편집기에 다양한 AI 도구가 추가되었습니다.", website: "https://filmora.wondershare.com", releaseDate: "2015", pricing: "Paid", tags: ["Editor", "Desktop"], thumbnail: "https://logo.clearbit.com/wondershare.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 4. Voice (음성/음악) - 총 20개
  {
    id: "voice-01", name: "ElevenLabs", category: "voice",
    summary: "가장 자연스러운 TTS.",
    description: "감정 표현이 가능한 최고의 텍스트 음성 변환 AI입니다.",
    website: "https://elevenlabs.io", releaseDate: "2023.01", pricing: "Free / Paid", tags: ["TTS", "Voice Cloning"],
    thumbnail: "https://logo.clearbit.com/elevenlabs.io",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "voice-02", name: "Suno", category: "voice", summary: "AI 작곡 혁명.", description: "가사와 스타일만 입력하면 노래를 작곡하고 불러줍니다.", website: "https://suno.com", releaseDate: "2023.12", pricing: "Free / Paid", tags: ["Music", "Song"], thumbnail: "https://logo.clearbit.com/suno.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-03", name: "Udio", category: "voice", summary: "고음질 음악 생성.", description: "음질이 뛰어나고 음악적 구조가 탄탄한 노래를 생성합니다.", website: "https://udio.com", releaseDate: "2024.04", pricing: "Free / Paid", tags: ["High Fidelity", "Music"], thumbnail: "https://logo.clearbit.com/udio.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-04", name: "Murf AI", category: "voice", summary: "스튜디오 품질의 AI 보이스오버.", description: "영상 내레이션 및 프레젠테이션용 보이스 생성.", website: "https://murf.ai", releaseDate: "2020.10", pricing: "Free / Paid", tags: ["Voiceover", "Studio"], thumbnail: "https://logo.clearbit.com/murf.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-05", name: "PlayHT", category: "voice", summary: "초현실적인 AI 음성 생성기.", description: "팟캐스트 및 오디오북 제작에 최적화되어 있습니다.", website: "https://play.ht", releaseDate: "2020.08", pricing: "Free / Paid", tags: ["Podcast", "Ultra Realistic"], thumbnail: "https://logo.clearbit.com/play.ht", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-06", name: "Lovo", category: "voice", summary: "감정 표현이 풍부한 AI 성우.", description: "다양한 감정과 스타일의 목소리를 제공합니다.", website: "https://lovo.ai", releaseDate: "2019.11", pricing: "Free / Paid", tags: ["Genny", "Emotion"], thumbnail: "https://logo.clearbit.com/lovo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-07", name: "Speechify", category: "voice", summary: "텍스트를 오디오로 읽어주는 도구.", description: "문서, 웹페이지를 듣기 편한 음성으로 변환합니다.", website: "https://speechify.com", releaseDate: "2017.01", pricing: "Free / Paid", tags: ["Productivity", "Reading"], thumbnail: "https://logo.clearbit.com/speechify.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-08", name: "Voiser", category: "voice", summary: "한국어 특화 AI 성우 서비스.", description: "자연스러운 한국어 발음과 다양한 캐릭터 보이스.", website: "https://voiser.co.kr", releaseDate: "2021.03", pricing: "Free / Paid", tags: ["Korean", "Voice Actor"], thumbnail: "https://logo.clearbit.com/voiser.co.kr", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-09", name: "Resemble AI", category: "voice", summary: "실시간 음성 변조 및 클로닝.", description: "게임 및 보안용 음성 복제 기술.", website: "https://resemble.ai", releaseDate: "2019.02", pricing: "Paid", tags: ["Cloning", "Security"], thumbnail: "https://logo.clearbit.com/resemble.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-10", name: "Descript", category: "voice", summary: "오디오 편집을 문서 편집처럼.", description: "텍스트를 수정하면 오디오도 수정되는 편집 툴.", website: "https://descript.com", releaseDate: "2017.12", pricing: "Free / Paid", tags: ["Editing", "Podcast"], thumbnail: "https://logo.clearbit.com/descript.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-11", name: "Riffusion", category: "voice", summary: "이미지에서 음악을 생성.", description: "소펙트로그램 이미지를 통해 음악을 생성하는 독특한 AI입니다.", website: "https://www.riffusion.com", releaseDate: "2022", pricing: "Free", tags: ["Experimental", "Music"], thumbnail: "https://logo.clearbit.com/riffusion.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-12", name: "Soundraw", category: "voice", summary: "저작권 없는 AI 음악 생성.", description: "영상 배경음악으로 쓰기 좋은 음악을 커스터마이징합니다.", website: "https://soundraw.io", releaseDate: "2020", pricing: "Free / Paid", tags: ["BGM", "Creator"], thumbnail: "https://logo.clearbit.com/soundraw.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-13", name: "AIVA", category: "voice", summary: "클래식 및 영화 음악 작곡.", description: "감동적인 오케스트라 및 영화 음악 스타일에 강점이 있습니다.", website: "https://aiva.ai", releaseDate: "2016", pricing: "Free / Paid", tags: ["Composer", "Orchestra"], thumbnail: "https://logo.clearbit.com/aiva.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-14", name: "Boomy", category: "voice", summary: "누구나 쉽게 노래 만들기.", description: "몇 번의 클릭으로 노래를 만들고 스트리밍 사이트에 배포까지 가능합니다.", website: "https://boomy.com", releaseDate: "2019", pricing: "Free / Paid", tags: ["Easy", "Distribution"], thumbnail: "https://logo.clearbit.com/boomy.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-15", name: "Uberduck", category: "voice", summary: "래퍼 목소리 생성 및 비트 제작.", description: "유명인의 목소리(패러디)나 랩 보이스 생성에 특화되어 있습니다.", website: "https://uberduck.ai", releaseDate: "2020", pricing: "Free / Paid", tags: ["Rap", "Parody"], thumbnail: "https://logo.clearbit.com/uberduck.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-16", name: "WellSaid Labs", category: "voice", summary: "기업용 고품질 TTS.", description: "매우 자연스럽고 전문적인 성우 톤의 목소리를 제공합니다.", website: "https://wellsaidlabs.com", releaseDate: "2018", pricing: "Paid", tags: ["Enterprise", "Professional"], thumbnail: "https://logo.clearbit.com/wellsaidlabs.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-17", name: "Listnr", category: "voice", summary: "팟캐스트 제작 및 호스팅.", description: "텍스트를 팟캐스트로 변환하고 배포까지 도와주는 플랫폼입니다.", website: "https://listnr.tech", releaseDate: "2020", pricing: "Paid", tags: ["Podcast", "Hosting"], thumbnail: "https://logo.clearbit.com/listnr.tech", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-18", name: "Krisp", category: "voice", summary: "AI 노이즈 캔슬링.", description: "통화 중 주변 소음을 실시간으로 제거해주는 도구입니다.", website: "https://krisp.ai", releaseDate: "2017", pricing: "Free / Paid", tags: ["Utility", "Noise Cancellation"], thumbnail: "https://logo.clearbit.com/krisp.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-19", name: "Otter.ai", category: "voice", summary: "회의 녹음 및 실시간 전사.", description: "영어 회의 내용을 실시간으로 받아적고 요약해줍니다.", website: "https://otter.ai", releaseDate: "2016", pricing: "Free / Paid", tags: ["Meeting", "Transcription"], thumbnail: "https://logo.clearbit.com/otter.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-20", name: "Fireflies.ai", category: "voice", summary: "AI 회의 어시스턴트.", description: "다양한 화상 회의 툴과 연동되어 회의 내용을 기록하고 분석합니다.", website: "https://fireflies.ai", releaseDate: "2020", pricing: "Free / Paid", tags: ["Meeting", "Summary"], thumbnail: "https://logo.clearbit.com/fireflies.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 5. Automation (자동화) - 총 20개
  // =====================================================================================
  {
    id: "auto-01", name: "n8n", category: "automation",
    description: "워크플로우 자동화를 위한 공정한 코드 기반 툴.",
    summary: "복잡한 업무 자동화도 노코드로 해결",
    website: "https://n8n.io", releaseDate: "2019.10", pricing: "Free / Enterprise", tags: ["Workflow", "No-code"],
    thumbnail: "https://logo.clearbit.com/n8n.io",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "auto-02", name: "Make", category: "automation", summary: "시각적 자동화 도구.", description: "직관적인 비주얼 오토메이션 플랫폼.", website: "https://make.com", releaseDate: "2016", pricing: "Free / Paid", tags: ["Workflow", "Integration"], thumbnail: "https://logo.clearbit.com/make.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-03", name: "Zapier", category: "automation", summary: "가장 많은 앱을 연동하는 자동화.", description: "5000개 이상의 앱을 손쉽게 연결.", website: "https://zapier.com", releaseDate: "2011.08", pricing: "Free / Paid", tags: ["Integration", "Easy"], thumbnail: "https://logo.clearbit.com/zapier.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-04", name: "Bardeen", category: "automation", summary: "브라우저 기반 AI 자동화.", description: "웹 브라우저에서 반복 작업을 대신해주는 AI.", website: "https://bardeen.ai", releaseDate: "2020.05", pricing: "Free / Paid", tags: ["Browser", "Scraping"], thumbnail: "https://logo.clearbit.com/bardeen.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-05", name: "UiPath", category: "automation", summary: "엔터프라이즈급 RPA 플랫폼.", description: "대규모 기업 업무 자동화의 표준.", website: "https://uipath.com", releaseDate: "2005", pricing: "Enterprise", tags: ["RPA", "Enterprise"], thumbnail: "https://logo.clearbit.com/uipath.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-06", name: "Power Automate", category: "automation", summary: "Microsoft 생태계 자동화.", description: "윈도우 및 오피스 앱과의 완벽한 연동.", website: "https://powerautomate.microsoft.com", releaseDate: "2016.10", pricing: "Paid", tags: ["Microsoft", "Desktop"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-07", name: "IFTTT", category: "automation", summary: "간단한 조건문 자동화.", description: "일상 생활 자동화에 최적화된 서비스.", website: "https://ifttt.com", releaseDate: "2010.12", pricing: "Free / Paid", tags: ["IoT", "Personal"], thumbnail: "https://logo.clearbit.com/ifttt.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-08", name: "Workato", category: "automation", summary: "비즈니스 프로세스 통합.", description: "IT와 비즈니스 팀을 위한 강력한 통합 툴.", website: "https://workato.com", releaseDate: "2013", pricing: "Enterprise", tags: ["Integration", "Business"], thumbnail: "https://logo.clearbit.com/workato.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-09", name: "Tray.io", category: "automation", summary: "로우코드 자동화 플랫폼.", description: "유연하고 확장성 높은 워크플로우 구축.", website: "https://tray.io", releaseDate: "2012", pricing: "Paid", tags: ["Low-code", "API"], thumbnail: "https://logo.clearbit.com/tray.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-10", name: "Relay.app", category: "automation", summary: "사람 개입 워크플로우 자동화.", description: "AI와 사람이 협업하는 자동화 프로세스.", website: "https://relay.app", releaseDate: "2023", pricing: "Free / Paid", tags: ["Collaboration", "Human-in-the-loop"], thumbnail: "https://logo.clearbit.com/relay.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-11", name: "ActivePieces", category: "automation", summary: "오픈소스 올인원 자동화.", description: "Zapier의 오픈소스 대안으로 주목받는 툴입니다.", website: "https://activepieces.com", releaseDate: "2022", pricing: "Open Source / Paid", tags: ["Open Source", "Self-hosted"], thumbnail: "https://logo.clearbit.com/activepieces.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-12", name: "Pipedream", category: "automation", summary: "개발자를 위한 연동 플랫폼.", description: "코드 레벨에서 상세한 제어가 가능한 자동화 툴입니다.", website: "https://pipedream.com", releaseDate: "2019", pricing: "Free / Paid", tags: ["Developer", "API"], thumbnail: "https://logo.clearbit.com/pipedream.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-13", name: "CheatLayer", category: "automation", summary: "GPT-4 기반 자동화 에이전트.", description: "자연어로 명령하면 자동화 스크립트를 짜주는 도구입니다.", website: "https://cheatlayer.com", releaseDate: "2021", pricing: "Paid", tags: ["GPT-4", "Scripting"], thumbnail: "https://logo.clearbit.com/cheatlayer.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-14", name: "Gumloop", category: "automation", summary: "AI 흐름 자동화 빌더.", description: "LLM 노드를 연결하여 복잡한 AI 작업을 자동화합니다.", website: "https://gumloop.com", releaseDate: "2023", pricing: "Free / Paid", tags: ["AI Flow", "Drag-drop"], thumbnail: "https://logo.clearbit.com/gumloop.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-15", name: "Axiom", category: "automation", summary: "브라우저 자동화 확장프로그램.", description: "반복적인 웹 작업을 녹화하여 자동 수행합니다.", website: "https://axiom.ai", releaseDate: "2019", pricing: "Free / Paid", tags: ["Browser", "No-code"], thumbnail: "https://logo.clearbit.com/axiom.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-16", name: "Browse AI", category: "automation", summary: "웹 데이터 추출 자동화.", description: "어떤 웹사이트든 모니터링하고 데이터를 추출합니다.", website: "https://browse.ai", releaseDate: "2021", pricing: "Free / Paid", tags: ["Scraping", "Data"], thumbnail: "https://logo.clearbit.com/browse.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-17", name: "Levity", category: "automation", summary: "비정형 데이터 워크플로우.", description: "이메일, 이미지, 텍스트 분류 등 AI 작업을 자동화합니다.", website: "https://levity.ai", releaseDate: "2020", pricing: "Paid", tags: ["Classification", "Workflow"], thumbnail: "https://logo.clearbit.com/levity.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-18", name: "Hexomatic", category: "automation", summary: "웹 스크래핑 및 자동화.", description: "노코드로 웹 데이터를 수집하고 가공하는 플랫폼.", website: "https://hexomatic.com", releaseDate: "2021", pricing: "Paid", tags: ["Scraping", "No-code"], thumbnail: "https://logo.clearbit.com/hexomatic.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-19", name: "Parabola", category: "automation", summary: "이커머스 데이터 자동화.", description: "쇼핑몰 운영에 필요한 데이터 처리를 자동화합니다.", website: "https://parabola.io", releaseDate: "2017", pricing: "Paid", tags: ["Ecommerce", "Data"], thumbnail: "https://logo.clearbit.com/parabola.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-20", name: "Appy Pie", category: "automation", summary: "노코드 앱 및 자동화 빌더.", description: "앱 개발부터 업무 자동화까지 하나로 해결.", website: "https://appypie.com", releaseDate: "2015", pricing: "Free / Paid", tags: ["App Builder", "No-code"], thumbnail: "https://logo.clearbit.com/appypie.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 6. Search (검색) - 총 20개 (기존 15 + 신규 5)
  // =====================================================================================
  {
    id: "search-01", name: "Perplexity", category: "search",
    description: "답변과 함께 출처를 제공하는 AI 검색.",
    summary: "신뢰할 수 있는 대화형 검색 엔진",
    website: "https://perplexity.ai", releaseDate: "2022.08", pricing: "Free / $20", tags: ["Search", "Citations"],
    thumbnail: "https://logo.clearbit.com/perplexity.ai",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "search-02", name: "Genspark", category: "search", summary: "목적 맞춤형 AI 검색 에이전트.", description: "특화된 스파크페이지를 생성하는 검색 AI.", website: "https://genspark.ai", releaseDate: "2024", pricing: "Free", tags: ["Agent", "Visual"], thumbnail: "https://logo.clearbit.com/genspark.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-03", name: "You.com", category: "search", summary: "개인화된 AI 검색 어시스턴트.", description: "다양한 모드를 제공하는 사생활 보호 검색.", website: "https://you.com", releaseDate: "2021.11", pricing: "Free / Paid", tags: ["Private", "Assistant"], thumbnail: "https://logo.clearbit.com/you.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-04", name: "Bing Chat", category: "search", summary: "GPT-4 기반 마이크로소프트 검색.", description: "웹 검색과 결합된 강력한 생성형 답변.", website: "https://bing.com/chat", releaseDate: "2023.02", pricing: "Free", tags: ["Microsoft", "GPT-4"], thumbnail: "https://logo.clearbit.com/bing.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-05", name: "Arc Search", category: "search", summary: "브라우저가 대신 검색.", description: "여러 페이지를 읽고 요약해주는 모바일 검색.", website: "https://arc.net", releaseDate: "2024.01", pricing: "Free", tags: ["Browser", "Summary"], thumbnail: "https://logo.clearbit.com/arc.net", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-06", name: "Komo", category: "search", summary: "광고 없는 빠르고 정확한 AI 검색.", description: "커뮤니티 중심의 인사이트 검색.", website: "https://komo.ai", releaseDate: "2022", pricing: "Free", tags: ["Ad-free", "Fast"], thumbnail: "https://logo.clearbit.com/komo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-07", name: "Phind", category: "search", summary: "개발자를 위한 AI 검색.", description: "코딩 질문에 최적화된 답변 제공.", website: "https://phind.com", releaseDate: "2023", pricing: "Free / Paid", tags: ["Developer", "Coding"], thumbnail: "https://logo.clearbit.com/phind.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-08", name: "Andi", category: "search", summary: "친근한 대화형 검색 챗봇.", description: "광고 없이 정보를 요약해주는 검색 친구.", website: "https://andisearch.com", releaseDate: "2022", pricing: "Free", tags: ["Chat", "Visual"], thumbnail: "https://logo.clearbit.com/andisearch.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-09", name: "Metaphor", category: "search", summary: "LLM을 위해 설계된 검색 API.", description: "AI가 이해하기 쉬운 형태의 검색 결과.", website: "https://exa.ai", releaseDate: "2023", pricing: "API", tags: ["API", "LLM"], thumbnail: "https://logo.clearbit.com/exa.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-10", name: "Consensus", category: "search", summary: "AI 기반 과학 논문 검색.", description: "연구 결과와 논문에서 신뢰할 수 있는 답변 추출.", website: "https://consensus.app", releaseDate: "2022", pricing: "Free / Paid", tags: ["Academic", "Science"], thumbnail: "https://logo.clearbit.com/consensus.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-11", name: "Elicit", category: "search", summary: "연구 논문 분석 비서.", description: "논문을 검색하고 핵심 내용을 요약해줍니다.", website: "https://elicit.com", releaseDate: "2021", pricing: "Free / Paid", tags: ["Research", "Paper"], thumbnail: "https://logo.clearbit.com/elicit.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-12", name: "SciSpace", category: "search", summary: "과학 논문 검색 및 이해.", description: "복잡한 논문을 쉽게 설명해주는 연구 도구입니다.", website: "https://typeset.io", releaseDate: "2020", pricing: "Free / Paid", tags: ["Science", "Explanation"], thumbnail: "https://logo.clearbit.com/typeset.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-13", name: "Tavily", category: "search", summary: "AI 에이전트를 위한 검색 API.", description: "LLM이 실시간 정보를 정확하게 검색하도록 돕습니다.", website: "https://tavily.com", releaseDate: "2023", pricing: "API", tags: ["Agent", "API"], thumbnail: "https://logo.clearbit.com/tavily.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-14", name: "SearchGPT", category: "search", summary: "OpenAI의 검색 프로토타입.", description: "대화형 AI와 실시간 검색의 결합 (정식 출시 대기 중).", website: "https://openai.com", releaseDate: "2024", pricing: "Waitlist", tags: ["OpenAI", "Prototype"], thumbnail: "https://logo.clearbit.com/openai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-15", name: "Gemini App", category: "search", summary: "Google 검색이 통합된 앱.", description: "구글 검색 결과와 생성형 답변을 동시에 제공합니다.", website: "https://gemini.google.com", releaseDate: "2024", pricing: "Free", tags: ["Google", "Integrated"], thumbnail: "https://logo.clearbit.com/google.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-16", name: "Brave Search AI", category: "search", summary: "개인정보 보호 AI 검색.", description: "추적 없이 요약된 검색 결과를 제공합니다.", website: "https://search.brave.com", releaseDate: "2023", pricing: "Free", tags: ["Privacy", "Summary"], thumbnail: "https://logo.clearbit.com/brave.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-17", name: "NeevaAI", category: "search", summary: "광고 없는 검색 (Snowflake 인수).", description: "신뢰할 수 있는 소스 기반의 요약 답변.", website: "https://neeva.com", releaseDate: "2023", pricing: "Shutdown", tags: ["Ad-free", "Citation"], thumbnail: "https://logo.clearbit.com/snowflake.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-18", name: "Waldo", category: "search", summary: "전문가를 위한 정밀 검색.", description: "데이터 포인트와 트렌드를 깊이 있게 검색합니다.", website: "https://www.waldo.fyi", releaseDate: "2022", pricing: "Paid", tags: ["Professional", "Deep"], thumbnail: "https://logo.clearbit.com/waldo.fyi", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-19", name: "Yep", category: "search", summary: "크리에이터 수익 공유 검색.", description: "Ahrefs가 만든, 콘텐츠 제작자를 지원하는 검색 엔진.", website: "https://yep.com", releaseDate: "2022", pricing: "Free", tags: ["Creator", "Fair"], thumbnail: "https://logo.clearbit.com/yep.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-20", name: "Globe Explorer", category: "search", summary: "시각적 지식 탐색 엔진.", description: "트리 구조로 정보를 시각화하여 탐색합니다.", website: "https://explorer.globe.engineer", releaseDate: "2023", pricing: "Free", tags: ["Visual", "Knowledge"], thumbnail: "https://logo.clearbit.com/globe.engineer", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 7. Agent (AI 에이전트) - 총 30개
  // =====================================================================================
  { id: "agent-01", name: "AutoGPT", category: "agent", summary: "자율 AI 에이전트의 시초.", description: "목표를 설정하면 스스로 계획을 세우고 실행하는 오픈소스 에이전트.", website: "https://news.agpt.co", releaseDate: "2023.03", pricing: "Open Source", tags: ["Autonomous", "Open Source"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-02", name: "BabyAGI", category: "agent", summary: "간결한 작업 관리 에이전트.", description: "작업을 생성하고 우선순위를 정해 실행하는 파이썬 스크립트.", website: "https://github.com/yoheinakajima/babyagi", releaseDate: "2023.03", pricing: "Open Source", tags: ["Task", "Python"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-03", name: "AgentGPT", category: "agent", summary: "웹에서 실행하는 자율 에이전트.", description: "브라우저에서 바로 목표를 입력하고 실행 과정을 지켜볼 수 있습니다.", website: "https://agentgpt.reworkd.ai", releaseDate: "2023.04", pricing: "Free / Paid", tags: ["Web", "Easy"], thumbnail: "https://logo.clearbit.com/reworkd.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-04", name: "Godmode", category: "agent", summary: "AutoGPT를 쉽게 웹에서.", description: "복잡한 설치 없이 자율 에이전트의 기능을 웹에서 체험합니다.", website: "https://godmode.space", releaseDate: "2023.05", pricing: "Free", tags: ["Web", "AutoGPT"], thumbnail: "https://logo.clearbit.com/godmode.space", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-05", name: "Cognosys", category: "agent", summary: "생산성을 위한 AI 에이전트.", description: "복잡한 워크플로우를 대화형으로 처리해주는 웹 기반 에이전트.", website: "https://cognosys.ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["Productivity", "Web"], thumbnail: "https://logo.clearbit.com/cognosys.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-06", name: "Lindy", category: "agent", summary: "모든 업무를 처리하는 AI 비서.", description: "이메일 관리, 일정 예약 등 개인 비서 역할을 수행합니다.", website: "https://lindy.ai", releaseDate: "2023", pricing: "Paid", tags: ["Assistant", "Task"], thumbnail: "https://logo.clearbit.com/lindy.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-07", name: "MultiOn", category: "agent", summary: "웹 브라우저 자동화 에이전트.", description: "유저 대신 웹사이트를 돌아다니며 예약, 주문 등을 수행합니다.", website: "https://www.multion.ai", releaseDate: "2023", pricing: "Paid", tags: ["Browser", "Action"], thumbnail: "https://logo.clearbit.com/multion.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-08", name: "HyperWrite PA", category: "agent", summary: "개인용 브라우저 어시스턴트.", description: "웹 서핑과 작업 수행을 도와주는 똑똑한 에이전트입니다.", website: "https://hyperwriteai.com", releaseDate: "2023", pricing: "Free / Paid", tags: ["Assistant", "Writing"], thumbnail: "https://logo.clearbit.com/hyperwriteai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-09", name: "Adept", category: "agent", summary: "소프트웨어 도구 사용 에이전트.", description: "사람이 소프트웨어를 쓰는 방식을 학습하여 도구를 대신 조작합니다.", website: "https://adept.ai", releaseDate: "2022", pricing: "Enterprise", tags: ["Tools", "Action"], thumbnail: "https://logo.clearbit.com/adept.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-10", name: "MetaGPT", category: "agent", summary: "멀티 에이전트 프레임워크.", description: "여러 AI 역할(기획자, 개발자 등)을 부여하여 협업하게 만듭니다.", website: "https://github.com/geekan/MetaGPT", releaseDate: "2023", pricing: "Open Source", tags: ["Multi-Agent", "Coding"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-11", name: "ChatDev", category: "agent", summary: "가상 소프트웨어 회사.", description: "AI들이 채팅하며 소프트웨어를 개발하는 시뮬레이션 환경.", website: "https://github.com/OpenBMB/ChatDev", releaseDate: "2023", pricing: "Open Source", tags: ["Simulation", "Dev"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-12", name: "OpenInterpreter", category: "agent", summary: "로컬 코드 실행 에이전트.", description: "자연어로 컴퓨터를 제어하고 코드를 실행하는 오픈소스 도구.", website: "https://openinterpreter.com", releaseDate: "2023", pricing: "Open Source", tags: ["Local", "Code"], thumbnail: "https://logo.clearbit.com/openinterpreter.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-13", name: "CrewAI", category: "agent", summary: "롤플레잉 자율 에이전트 팀.", description: "LangChain 기반으로 여러 에이전트가 협업하는 워크플로우 구축.", website: "https://crewai.com", releaseDate: "2023", pricing: "Open Source", tags: ["Framework", "Roleplay"], thumbnail: "https://logo.clearbit.com/crewai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-14", name: "AutoGen", category: "agent", summary: "Microsoft의 멀티 에이전트.", description: "대화형 에이전트들을 커스터마이징하고 협업시키는 프레임워크.", website: "https://microsoft.github.io/autogen", releaseDate: "2023", pricing: "Open Source", tags: ["Microsoft", "Framework"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-15", name: "SuperAGI", category: "agent", summary: "오픈소스 자율 에이전트 프레임워크.", description: "에이전트를 쉽게 구축, 관리, 실행할 수 있는 플랫폼.", website: "https://superagi.com", releaseDate: "2023", pricing: "Open Source", tags: ["Platform", "Dev"], thumbnail: "https://logo.clearbit.com/superagi.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-16", name: "BabyCatAGI", category: "agent", summary: "BabyAGI의 개선된 버전.", description: "기존 BabyAGI 코드의 기능을 확장하고 개선한 프로젝트.", website: "https://github.com", releaseDate: "2023", pricing: "Open Source", tags: ["Mod", "Experimental"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-17", name: "MiniAGI", category: "agent", summary: "최소한의 자율 에이전트.", description: "GPT-4 기반의 간단하고 강력한 에이전트 구현체.", website: "https://github.com", releaseDate: "2023", pricing: "Open Source", tags: ["Simple", "GPT-4"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-18", name: "Jarvis (HuggingGPT)", category: "agent", summary: "모든 AI 모델을 연결.", description: "LLM을 컨트롤러로 사용하여 Hugging Face의 다양한 모델을 활용.", website: "https://github.com/microsoft/JARVIS", releaseDate: "2023", pricing: "Open Source", tags: ["Hub", "Connection"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-19", name: "ChaosGPT", category: "agent", summary: "AutoGPT의 파괴적인 버전.", description: "AI 안전성을 연구하기 위해 만들어진 실험적인 에이전트.", website: "https://twitter.com/chaos_gpt", releaseDate: "2023", pricing: "Free", tags: ["Experiment", "Safety"], thumbnail: "https://logo.clearbit.com/twitter.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-20", name: "ChemCrow", category: "agent", summary: "화학 연구 특화 에이전트.", description: "화학 도구를 사용하여 물질 합성 및 연구를 돕는 AI.", website: "https://github.com/ur-whitelab/chemcrow-public", releaseDate: "2023", pricing: "Open Source", tags: ["Science", "Chemistry"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-21", name: "Agent47", category: "agent", summary: "웹 크롤링 및 데이터 추출.", description: "웹상의 정보를 수집하고 가공하는 데 특화된 봇.", website: "#", releaseDate: "2023", pricing: "Free", tags: ["Crawling", "Data"], thumbnail: "", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-22", name: "BondAI", category: "agent", summary: "금융 데이터 분석 에이전트.", description: "시장 데이터를 분석하고 리포트를 작성하는 AI.", website: "#", releaseDate: "2023", pricing: "Paid", tags: ["Finance", "Analysis"], thumbnail: "", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-23", name: "Scout", category: "agent", summary: "시장 조사 자동화.", description: "경쟁사 분석 및 트렌드 조사를 대신해주는 에이전트.", website: "#", releaseDate: "2023", pricing: "Paid", tags: ["Market", "Research"], thumbnail: "", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-24", name: "XAgent", category: "agent", summary: "복잡한 작업 해결사.", description: "다단계 계획을 수립하고 실행하는 고성능 에이전트.", website: "https://github.com/OpenBMB/XAgent", releaseDate: "2023", pricing: "Open Source", tags: ["Complex", "Task"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-25", name: "TaskWeaver", category: "agent", summary: "코드 중심의 작업 수행.", description: "데이터 분석 및 도메인 특화 작업을 코드로 처리합니다.", website: "https://microsoft.github.io/TaskWeaver", releaseDate: "2023", pricing: "Open Source", tags: ["Code", "Data"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-26", name: "GPT Engineer", category: "agent", summary: "앱 전체를 코딩하는 AI.", description: "설명만 입력하면 전체 프로젝트 코드베이스를 생성합니다.", website: "https://gptengineer.app", releaseDate: "2023", pricing: "Free / Paid", tags: ["Coding", "Project"], thumbnail: "https://logo.clearbit.com/gptengineer.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-27", name: "SudoLang", category: "agent", summary: "AI를 위한 프로그래밍 언어.", description: "에이전트에게 지시를 내리기 위한 의사코드 언어 체계.", website: "https://github.com/paralleldrive/sudolang-llm-support", releaseDate: "2023", pricing: "Open Source", tags: ["Language", "Prompt"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-28", name: "BeeBot", category: "agent", summary: "개인 비서형 에이전트.", description: "일정 관리와 알림을 담당하는 가벼운 봇.", website: "#", releaseDate: "2023", pricing: "Free", tags: ["Personal", "Light"], thumbnail: "", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-29", name: "Character.ai", category: "agent", summary: "페르소나 챗봇.", description: "다양한 캐릭터와 대화할 수 있는 엔터테인먼트 에이전트.", website: "https://character.ai", releaseDate: "2022", pricing: "Free / Paid", tags: ["Chat", "Fun"], thumbnail: "https://logo.clearbit.com/character.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "agent-30", name: "Replika", category: "agent", summary: "AI 친구.", description: "사용자와 감정적인 유대를 쌓는 대화형 AI.", website: "https://replika.com", releaseDate: "2017", pricing: "Free / Paid", tags: ["Friend", "Emotion"], thumbnail: "https://logo.clearbit.com/replika.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 8. Coding (코딩 보조) - 총 20개
  // =====================================================================================
  { id: "code-01", name: "GitHub Copilot", category: "coding", summary: "AI 코딩 파트너.", description: "가장 널리 쓰이는 코드 자동 완성 및 제안 도구.", website: "https://github.com/features/copilot", releaseDate: "2021", pricing: "Paid", tags: ["Completion", "Microsoft"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-02", name: "Cursor", category: "coding", summary: "AI 네이티브 코드 에디터.", description: "VS Code 기반으로 AI 기능이 내장된 강력한 에디터.", website: "https://cursor.sh", releaseDate: "2023", pricing: "Free / Paid", tags: ["Editor", "Chat"], thumbnail: "https://logo.clearbit.com/cursor.sh", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-03", name: "Tabnine", category: "coding", summary: "프라이버시 중심 코드 완성.", description: "개인정보 보호를 중시하는 AI 코딩 어시스턴트.", website: "https://tabnine.com", releaseDate: "2018", pricing: "Free / Paid", tags: ["Privacy", "Completion"], thumbnail: "https://logo.clearbit.com/tabnine.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-04", name: "Codeium", category: "coding", summary: "빠르고 무료인 코딩 도구.", description: "개인 개발자에게 무료로 제공되는 고성능 자동 완성.", website: "https://codeium.com", releaseDate: "2022", pricing: "Free / Enterprise", tags: ["Free", "Fast"], thumbnail: "https://logo.clearbit.com/codeium.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-05", name: "Amazon Q Developer", category: "coding", summary: "AWS 특화 코딩 도구.", description: "AWS 서비스 통합 및 코드 생성을 돕는 (구 CodeWhisperer).", website: "https://aws.amazon.com/q/developer", releaseDate: "2022", pricing: "Free / Paid", tags: ["AWS", "Cloud"], thumbnail: "https://logo.clearbit.com/amazon.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-06", name: "Replit Ghostwriter", category: "coding", summary: "온라인 IDE 내장 AI.", description: "Replit 환경에서 바로 코드를 짜고 디버깅하는 AI.", website: "https://replit.com", releaseDate: "2022", pricing: "Paid", tags: ["Cloud IDE", "Web"], thumbnail: "https://logo.clearbit.com/replit.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-07", name: "Sourcegraph Cody", category: "coding", summary: "코드베이스 이해 AI.", description: "전체 프로젝트 코드를 읽고 문맥에 맞는 답변을 제공.", website: "https://sourcegraph.com/cody", releaseDate: "2023", pricing: "Free / Paid", tags: ["Context", "Search"], thumbnail: "https://logo.clearbit.com/sourcegraph.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-08", name: "Bito", category: "coding", summary: "IDE용 AI 챗봇.", description: "코드 설명, 테스트 생성 등을 돕는 플러그인.", website: "https://bito.ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["Chat", "Plugin"], thumbnail: "https://logo.clearbit.com/bito.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-09", name: "Blackbox AI", category: "coding", summary: "개발자를 위한 AI 검색.", description: "코딩 질문에 특화된 검색 및 자동 완성.", website: "https://blackbox.ai", releaseDate: "2022", pricing: "Free / Paid", tags: ["Search", "Snippet"], thumbnail: "https://logo.clearbit.com/blackbox.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-10", name: "AskCodi", category: "coding", summary: "코딩 질문 해결사.", description: "다양한 언어를 지원하는 코딩 보조 도구.", website: "https://askcodi.com", releaseDate: "2022", pricing: "Free / Paid", tags: ["Helper", "Multi-lang"], thumbnail: "https://logo.clearbit.com/askcodi.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-11", name: "CodiumAI", category: "coding", summary: "AI 테스트 코드 생성.", description: "코드의 무결성을 검증하는 테스트 케이스를 자동 생성.", website: "https://codium.ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["Testing", "QA"], thumbnail: "https://logo.clearbit.com/codium.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-12", name: "Mintlify", category: "coding", summary: "코드 문서 자동화.", description: "코드를 분석해 아름다운 문서를 자동으로 만들어줍니다.", website: "https://mintlify.com", releaseDate: "2022", pricing: "Free / Paid", tags: ["Documentation", "Writer"], thumbnail: "https://logo.clearbit.com/mintlify.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-13", name: "Mutable.ai", category: "coding", summary: "AI 가속 코딩.", description: "고품질 코드를 빠르게 작성하도록 돕는 플랫폼.", website: "https://mutable.ai", releaseDate: "2022", pricing: "Paid", tags: ["Speed", "Quality"], thumbnail: "https://logo.clearbit.com/mutable.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-14", name: "What The Diff", category: "coding", summary: "코드 리뷰 자동화.", description: "PR(Pull Request) 내용을 요약하고 설명해주는 AI.", website: "https://whatthediff.ai", releaseDate: "2022", pricing: "Free / Paid", tags: ["Review", "Git"], thumbnail: "https://logo.clearbit.com/whatthediff.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-15", name: "Adrenaline", category: "coding", summary: "코드 디버깅 도우미.", description: "에러의 원인을 찾고 수정 방안을 제시합니다.", website: "https://useadrenaline.com", releaseDate: "2023", pricing: "Free", tags: ["Debug", "Fix"], thumbnail: "https://logo.clearbit.com/useadrenaline.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-16", name: "CodeGeeX", category: "coding", summary: "다국어 코드 생성 모델.", description: "다양한 프로그래밍 언어를 지원하는 오픈 모델.", website: "https://codegeex.cn", releaseDate: "2022", pricing: "Open Source", tags: ["Multi-lang", "Open"], thumbnail: "https://logo.clearbit.com/codegeex.cn", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-17", name: "FauxPilot", category: "coding", summary: "자체 호스팅 Copilot.", description: "GitHub Copilot의 오픈소스 대안 서버.", website: "https://github.com/fauxpilot/fauxpilot", releaseDate: "2022", pricing: "Open Source", tags: ["Self-hosted", "Alternative"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-18", name: "GPT-Code-Clippy", category: "coding", summary: "오픈소스 코딩 어시스턴트.", description: "GPT-Neo 등을 기반으로 한 코딩 도구.", website: "https://github.com/CrankySupertoon/GPT-Code-Clippy", releaseDate: "2021", pricing: "Open Source", tags: ["Community", "Project"], thumbnail: "https://logo.clearbit.com/github.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-19", name: "Refact.ai", category: "coding", summary: "AI 코딩 및 채팅.", description: "개인화된 미세조정이 가능한 코딩 툴.", website: "https://refact.ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["Fine-tune", "Chat"], thumbnail: "https://logo.clearbit.com/refact.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "code-20", name: "Fig", category: "coding", summary: "터미널 자동 완성.", description: "터미널 명령어를 시각적으로 추천해주는 도구 (Amazon 인수).", website: "https://fig.io", releaseDate: "2020", pricing: "Free", tags: ["Terminal", "CLI"], thumbnail: "https://logo.clearbit.com/fig.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 9. Design (디자인/3D) - 총 20개
  // =====================================================================================
  { id: "design-01", name: "Canva", category: "design", summary: "누구나 쉽게 하는 AI 디자인.", description: "Magic Studio 기능을 통해 이미지, 텍스트 등을 AI로 편집.", website: "https://canva.com", releaseDate: "2013", pricing: "Free / Paid", tags: ["Easy", "Graphic"], thumbnail: "https://logo.clearbit.com/canva.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-02", name: "Figma AI", category: "design", summary: "UI/UX 디자인의 미래.", description: "디자인 자동화 및 생성 기능을 갖춘 협업 툴.", website: "https://figma.com", releaseDate: "2016", pricing: "Free / Paid", tags: ["UI/UX", "Pro"], thumbnail: "https://logo.clearbit.com/figma.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-03", name: "Uizard", category: "design", summary: "스케치를 UI로 변환.", description: "손그림이나 텍스트로 앱/웹 디자인 시안을 생성.", website: "https://uizard.io", releaseDate: "2018", pricing: "Free / Paid", tags: ["Prototype", "Wireframe"], thumbnail: "https://logo.clearbit.com/uizard.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-04", name: "Galileo AI", category: "design", summary: "텍스트 투 UI 디자인.", description: "설명만으로 고퀄리티 인터페이스 디자인을 생성.", website: "https://usegalileo.ai", releaseDate: "2023", pricing: "Paid", tags: ["Generative UI", "Figma"], thumbnail: "https://logo.clearbit.com/usegalileo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-05", name: "Visily", category: "design", summary: "AI 기반 와이어프레임.", description: "스크린샷을 편집 가능한 디자인으로 변환.", website: "https://visily.ai", releaseDate: "2021", pricing: "Free", tags: ["Screenshot-to-Design"], thumbnail: "https://logo.clearbit.com/visily.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-06", name: "Khroma", category: "design", summary: "AI 컬러 팔레트 생성.", description: "사용자 취향을 학습하여 무한한 색상 조합을 추천.", website: "https://khroma.co", releaseDate: "2018", pricing: "Free", tags: ["Color", "Inspiration"], thumbnail: "https://logo.clearbit.com/khroma.co", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-07", name: "Fontjoy", category: "design", summary: "AI 폰트 페어링.", description: "가장 잘 어울리는 폰트 조합을 찾아줍니다.", website: "https://fontjoy.com", releaseDate: "2017", pricing: "Free", tags: ["Font", "Typography"], thumbnail: "https://logo.clearbit.com/fontjoy.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-08", name: "Looka", category: "design", summary: "AI 로고 메이커.", description: "브랜드 아이덴티티에 맞는 로고와 브랜드 키트 생성.", website: "https://looka.com", releaseDate: "2016", pricing: "Paid", tags: ["Logo", "Brand"], thumbnail: "https://logo.clearbit.com/looka.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-09", name: "Brandmark", category: "design", summary: "스마트한 로고 디자인.", description: "AI를 활용해 즉시 로고와 브랜드 가이드를 제작.", website: "https://brandmark.io", releaseDate: "2018", pricing: "Paid", tags: ["Logo", "Minimal"], thumbnail: "https://logo.clearbit.com/brandmark.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-10", name: "Tailor Brands", category: "design", summary: "원스톱 브랜딩 플랫폼.", description: "로고부터 소셜 미디어 디자인까지 자동화.", website: "https://tailorbrands.com", releaseDate: "2014", pricing: "Paid", tags: ["Branding", "Business"], thumbnail: "https://logo.clearbit.com/tailorbrands.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-11", name: "Designs.ai", category: "design", summary: "올인원 크리에이티브.", description: "로고, 영상, 배너, 목업 등을 AI로 생성.", website: "https://designs.ai", releaseDate: "2019", pricing: "Paid", tags: ["Suite", "Marketing"], thumbnail: "https://logo.clearbit.com/designs.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-12", name: "Patterned.ai", category: "design", summary: "AI 패턴 생성기.", description: "텍스트 설명으로 반복 가능한 패턴 이미지를 생성.", website: "https://patterned.ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["Pattern", "Texture"], thumbnail: "https://logo.clearbit.com/patterned.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-13", name: "Visual Electric", category: "design", summary: "디자이너를 위한 생성형 캔버스.", description: "무한 캔버스에서 아이디어를 시각화하는 도구.", website: "https://visualelectric.com", releaseDate: "2023", pricing: "Free / Paid", tags: ["Canvas", "Moodboard"], thumbnail: "https://logo.clearbit.com/visualelectric.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-14", name: "Illustroke", category: "design", summary: "텍스트 투 벡터 일러스트.", description: "간단한 설명으로 벡터 일러스트레이션을 생성.", website: "https://illustroke.com", releaseDate: "2023", pricing: "Paid", tags: ["Vector", "Illustration"], thumbnail: "https://logo.clearbit.com/illustroke.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-15", name: "Vectorizer.ai", category: "design", summary: "이미지를 벡터로 변환.", description: "비트맵 이미지를 SVG 벡터로 깔끔하게 변환.", website: "https://vectorizer.ai", releaseDate: "2023", pricing: "Paid", tags: ["Converter", "SVG"], thumbnail: "https://logo.clearbit.com/vectorizer.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-16", name: "Autodraw", category: "design", summary: "구글의 낙서 보정 AI.", description: "대충 그린 낙서를 멋진 아이콘으로 바꿔줍니다.", website: "https://autodraw.com", releaseDate: "2017", pricing: "Free", tags: ["Sketch", "Google"], thumbnail: "https://logo.clearbit.com/autodraw.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-17", name: "Flair.ai", category: "design", summary: "제품 사진 촬영 AI.", description: "제품 이미지를 업로드하면 멋진 배경을 합성해줍니다.", website: "https://flair.ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["Product", "Photo"], thumbnail: "https://logo.clearbit.com/flair.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-18", name: "Magician", category: "design", summary: "Figma용 AI 플러그인.", description: "Figma 내에서 아이콘, 이미지, 텍스트를 생성.", website: "https://magician.design", releaseDate: "2022", pricing: "Paid", tags: ["Figma", "Plugin"], thumbnail: "https://logo.clearbit.com/magician.design", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-19", name: "Luma Genie", category: "design", summary: "3D 모델 생성 AI.", description: "텍스트로 3D 자산을 빠르게 생성합니다.", website: "https://lumalabs.ai/genie", releaseDate: "2023", pricing: "Free / Paid", tags: ["3D", "Asset"], thumbnail: "https://logo.clearbit.com/lumalabs.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "design-20", name: "Spline AI", category: "design", summary: "AI 3D 디자인 툴.", description: "프롬프트로 3D 씬과 객체를 생성하고 편집.", website: "https://spline.design/ai", releaseDate: "2023", pricing: "Free / Paid", tags: ["3D", "Web"], thumbnail: "https://logo.clearbit.com/spline.design", rating: 0, ratingCount: 0, userRatings: [], comments: [] },


  // =====================================================================================
  // 10. Productivity (생산성/문서) - 총 20개
  // =====================================================================================
  { id: "prod-01", name: "Notion AI", category: "productivity", summary: "노션 안의 AI 비서.", description: "글쓰기, 요약, 번역 등 노션 워크스페이스 내 작업 보조.", website: "https://notion.so", releaseDate: "2023.02", pricing: "Paid", tags: ["Note", "Docs"], thumbnail: "https://logo.clearbit.com/notion.so", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-02", name: "Jasper", category: "productivity", summary: "마케팅 콘텐츠 생성.", description: "블로그, 광고 문구 등 마케팅에 특화된 글쓰기 AI.", website: "https://jasper.ai", releaseDate: "2021.01", pricing: "Paid", tags: ["Marketing", "Copywriting"], thumbnail: "https://logo.clearbit.com/jasper.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-03", name: "Copy.ai", category: "productivity", summary: "카피라이팅 자동화.", description: "다양한 템플릿으로 빠른 카피라이팅 지원.", website: "https://copy.ai", releaseDate: "2020.10", pricing: "Free / Paid", tags: ["Copywriting", "Social"], thumbnail: "https://logo.clearbit.com/copy.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-04", name: "Writesonic", category: "productivity", summary: "SEO 최적화 글쓰기.", description: "검색 엔진 상위 노출을 위한 콘텐츠 작성.", website: "https://writesonic.com", releaseDate: "2020", pricing: "Free / Paid", tags: ["SEO", "Blog"], thumbnail: "https://logo.clearbit.com/writesonic.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-05", name: "Rytr", category: "productivity", summary: "가성비 좋은 글쓰기 툴.", description: "저렴하고 사용하기 쉬운 AI 작가.", website: "https://rytr.me", releaseDate: "2021.04", pricing: "Free / Paid", tags: ["Writing", "Budget"], thumbnail: "https://logo.clearbit.com/rytr.me", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-06", name: "GrammarlyGO", category: "productivity", summary: "AI 문법 교정 및 작성.", description: "영어 문법 교정을 넘어 문맥에 맞는 글쓰기 제안.", website: "https://grammarly.com", releaseDate: "2023", pricing: "Free / Paid", tags: ["Grammar", "Correction"], thumbnail: "https://logo.clearbit.com/grammarly.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-07", name: "DeepL", category: "productivity", summary: "가장 자연스러운 번역기.", description: "뉘앙스를 살리는 고품질 AI 번역.", website: "https://deepl.com", releaseDate: "2017.08", pricing: "Free / Paid", tags: ["Translation", "Language"], thumbnail: "https://logo.clearbit.com/deepl.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-08", name: "Quillbot", category: "productivity", summary: "패러프레이징 도구.", description: "문장을 재구성하여 표절을 피하고 표현을 다듬는 툴.", website: "https://quillbot.com", releaseDate: "2017", pricing: "Free / Paid", tags: ["Paraphrase", "Writing"], thumbnail: "https://logo.clearbit.com/quillbot.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-09", name: "Wordtune", category: "productivity", summary: "문장 다듬기 비서.", description: "글의 톤앤매너를 조절하고 문장을 매끄럽게 수정.", website: "https://wordtune.com", releaseDate: "2020", pricing: "Free / Paid", tags: ["Editor", "Tone"], thumbnail: "https://logo.clearbit.com/wordtune.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-10", name: "Mem.ai", category: "productivity", summary: "AI 기반 노트 앱.", description: "저장된 정보를 스스로 정리하고 연결해주는 스마트 노트.", website: "https://mem.ai", releaseDate: "2019", pricing: "Free / Paid", tags: ["Note", "Knowledge"], thumbnail: "https://logo.clearbit.com/mem.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-11", name: "Rewind", category: "productivity", summary: "나의 모든 디지털 기록.", description: "화면, 소리 등 내가 보고 들은 모든 것을 기억하고 검색.", website: "https://rewind.ai", releaseDate: "2022", pricing: "Paid", tags: ["Memory", "Mac"], thumbnail: "https://logo.clearbit.com/rewind.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-12", name: "Tana", category: "productivity", summary: "AI가 결합된 지식 관리.", description: "모든 것을 노드(Node)로 관리하는 새로운 방식의 생산성 툴.", website: "https://tana.inc", releaseDate: "2022", pricing: "Paid", tags: ["PKM", "Database"], thumbnail: "https://logo.clearbit.com/tana.inc", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-13", name: "Gamma", category: "productivity", summary: "AI 프레젠테이션 생성.", description: "텍스트만 입력하면 디자인된 슬라이드와 문서를 생성.", website: "https://gamma.app", releaseDate: "2022", pricing: "Free / Paid", tags: ["Slide", "Design"], thumbnail: "https://logo.clearbit.com/gamma.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-14", name: "Beautiful.ai", category: "productivity", summary: "자동 디자인 슬라이드.", description: "내용을 넣으면 레이아웃을 알아서 잡아주는 PPT 툴.", website: "https://beautiful.ai", releaseDate: "2016", pricing: "Paid", tags: ["Presentation", "Design"], thumbnail: "https://logo.clearbit.com/beautiful.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-15", name: "Tome", category: "productivity", summary: "스토리텔링 형식의 슬라이드.", description: "모바일 친화적이고 인터랙티브한 스토리북 생성.", website: "https://tome.app", releaseDate: "2022", pricing: "Free / Paid", tags: ["Storytelling", "Slide"], thumbnail: "https://logo.clearbit.com/tome.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-16", name: "Decktopus", category: "productivity", summary: "가장 빠른 PPT 생성기.", description: "주제만 입력하면 완벽한 구조의 프레젠테이션 완성.", website: "https://decktopus.com", releaseDate: "2020", pricing: "Free / Paid", tags: ["Fast", "PPT"], thumbnail: "https://logo.clearbit.com/decktopus.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-17", name: "Sanebox", category: "productivity", summary: "AI 이메일 정리.", description: "중요한 메일만 남기고 나머지는 알아서 분류.", website: "https://sanebox.com", releaseDate: "2010", pricing: "Paid", tags: ["Email", "Organization"], thumbnail: "https://logo.clearbit.com/sanebox.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-18", name: "Mailbutler", category: "productivity", summary: "이메일 비서.", description: "이메일 요약, 할 일 생성, 스마트 답장 기능 제공.", website: "https://mailbutler.io", releaseDate: "2015", pricing: "Free / Paid", tags: ["Email", "Assistant"], thumbnail: "https://logo.clearbit.com/mailbutler.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-19", name: "Clockwise", category: "productivity", summary: "스마트 캘린더 관리.", description: "팀원들의 일정을 분석해 최적의 회의 시간을 제안.", website: "https://getclockwise.com", releaseDate: "2016", pricing: "Free / Paid", tags: ["Calendar", "Time"], thumbnail: "https://logo.clearbit.com/getclockwise.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "prod-20", name: "Reclaim.ai", category: "productivity", summary: "업무와 개인 일정 보호.", description: "중요한 업무 시간을 확보해주는 스마트 스케줄러.", website: "https://reclaim.ai", releaseDate: "2019", pricing: "Free / Paid", tags: ["Schedule", "Balance"], thumbnail: "https://logo.clearbit.com/reclaim.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
];