import { AiTool } from "@/types/content";

export const AI_TOOLS_DATA: AiTool[] = [
  // 1. LLM (대화형 AI)
  {
    id: "llm-01", name: "ChatGPT", category: "llm",
    description: "OpenAI가 개발한 가장 대중적인 대화형 AI.",
    summary: "대화형 AI의 표준, GPT-4o 탑재",
    website: "https://chat.openai.com", releaseDate: "2022.11", pricing: "Free / $20 mo", tags: ["Chat", "Coding", "Writing"],
    thumbnail: "https://logo.clearbit.com/openai.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  {
    id: "llm-02", name: "Claude 3", category: "llm",
    description: "Anthropic의 인간다운 대화형 AI.",
    summary: "가장 인간다운 문맥 이해력을 가진 AI",
    website: "https://claude.ai", releaseDate: "2024.03", pricing: "Free / $20 mo", tags: ["Long-context", "Writing"],
    thumbnail: "https://logo.clearbit.com/anthropic.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  {
    id: "llm-03", name: "Gemini", category: "llm",
    description: "Google의 멀티모달 AI 모델.",
    summary: "구글 생태계와 완벽하게 연동되는 멀티모달",
    website: "https://gemini.google.com", releaseDate: "2023.12", pricing: "Free / $20 mo", tags: ["Multimodal", "Google"],
    thumbnail: "https://logo.clearbit.com/google.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "llm-04", name: "Perplexity", category: "llm", summary: "실시간 검색 기반 답변 엔진.", description: "출처를 명시하는 검색 중심의 AI로, 최신 정보를 빠르게 찾는 데 최적화되어 있습니다.", releaseDate: "2022.08", website: "https://perplexity.ai", pricing: "Free / $20 mo", tags: ["Search", "Citations"], thumbnail: "https://logo.clearbit.com/perplexity.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-05", name: "Mistral", category: "llm", summary: "유럽 최고의 오픈소스 모델.", description: "효율적이고 강력한 성능을 자랑하는 프랑스발 오픈소스 LLM입니다.", releaseDate: "2023.09", website: "https://mistral.ai", pricing: "Open Source / API", tags: ["Open Source", "Efficient"], thumbnail: "https://logo.clearbit.com/mistral.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-06", name: "Llama 3", category: "llm", summary: "Meta의 강력한 오픈소스 모델.", description: "개인 및 상업적 용도로 사용 가능한 고성능 언어 모델입니다.", releaseDate: "2024.04", website: "https://llama.meta.com", pricing: "Open Source", tags: ["Meta", "Local LLM"], thumbnail: "https://logo.clearbit.com/meta.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-07", name: "Grok", category: "llm", summary: "xAI의 위트 있는 AI.", description: "X(트위터) 데이터를 실시간으로 반영하며, 약간의 유머감각을 가진 AI입니다.", releaseDate: "2023.11", website: "https://x.ai", pricing: "Paid (X Premium)", tags: ["Real-time", "Humor"], thumbnail: "https://logo.clearbit.com/x.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-08", name: "Cohere", category: "llm", summary: "기업용 RAG 특화 모델.", description: "기업 데이터 연결 및 검색 증강 생성(RAG)에 최적화된 엔터프라이즈 모델입니다.", releaseDate: "2022.06", website: "https://cohere.com", pricing: "API Pricing", tags: ["Enterprise", "RAG"], thumbnail: "https://logo.clearbit.com/cohere.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-09", name: "Pi", category: "llm", summary: "감성적인 대화 파트너.", description: "사용자의 감정을 이해하고 공감하는 데 초점을 맞춘 개인 비서 AI입니다.", releaseDate: "2023.05", website: "https://pi.ai", pricing: "Free", tags: ["Emotional", "Chat"], thumbnail: "https://logo.clearbit.com/pi.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "llm-10", name: "HyperCLOVA X", category: "llm", summary: "한국어에 가장 강한 AI.", description: "네이버가 개발한 한국어 특화 거대언어모델로, 한국 문화와 맥락을 깊이 이해합니다.", releaseDate: "2023.08", website: "https://clova.ai", pricing: "Enterprise", tags: ["Korean", "Naver"], thumbnail: "https://logo.clearbit.com/navercorp.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 2. Image (이미지 생성)
  {
    id: "img-01", name: "Midjourney", category: "image",
    summary: "가장 예술적인 이미지 생성기.",
    description: "Discord 기반으로 동작하며, 현존하는 AI 중 가장 뛰어난 예술적 화질을 자랑합니다.",
    releaseDate: "2022.07", website: "https://midjourney.com", pricing: "$10~$120 mo", tags: ["High Quality", "Art"],
    thumbnail: "https://logo.clearbit.com/midjourney.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "img-02", name: "Stable Diffusion", category: "image", summary: "로컬 설치 가능한 오픈소스.", description: "PC에 직접 설치하여 제약 없이 이미지를 생성할 수 있는 강력한 도구입니다.", releaseDate: "2022.08", website: "https://stability.ai", pricing: "Free (Open Source)", tags: ["Local", "ControlNet"], thumbnail: "https://logo.clearbit.com/stability.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-03", name: "Leonardo.ai", category: "image", summary: "게임 에셋과 아트에 특화.", description: "다양한 모델을 제공하며 특히 게임 아이템이나 캐릭터 생성에 탁월합니다.", releaseDate: "2022.12", website: "https://leonardo.ai", pricing: "Free / Paid", tags: ["Game Asset", "Easy UI"], thumbnail: "https://logo.clearbit.com/leonardo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-04", name: "DALL-E 3", category: "image", summary: "ChatGPT 안에서 그리는 그림.", description: "프롬프트를 정확하게 이해하고 텍스트 묘사 능력이 뛰어납니다.", releaseDate: "2023.10", website: "https://openai.com/dall-e-3", pricing: "Included in ChatGPT Plus", tags: ["Simple", "Text Rendering"], thumbnail: "https://logo.clearbit.com/openai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-05", name: "Adobe Firefly", category: "image", summary: "상업적 사용이 안전한 AI.", description: "어도비 스톡 이미지로 학습되어 저작권 문제 없이 상업적 이용이 가능합니다.", releaseDate: "2023.03", website: "https://firefly.adobe.com", pricing: "Free / Credits", tags: ["Commercial", "Photoshop"], thumbnail: "https://logo.clearbit.com/adobe.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-06", name: "Ideogram", category: "image", summary: "텍스트 타이포그래피 최강자.", description: "이미지 내에 정확한 글자를 삽입하는 능력이 매우 뛰어납니다.", releaseDate: "2023.08", website: "https://ideogram.ai", pricing: "Free / Paid", tags: ["Typography", "Logo"], thumbnail: "https://logo.clearbit.com/ideogram.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-07", name: "Krea AI", category: "image", summary: "실시간 드로잉 & 업스케일.", description: "그리는 즉시 AI가 이미지를 완성해주는 실시간 기능을 제공합니다.", releaseDate: "2023.11", website: "https://krea.ai", pricing: "Free / Paid", tags: ["Real-time", "Upscale"], thumbnail: "https://logo.clearbit.com/krea.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-08", name: "Magnific AI", category: "image", summary: "이미지 디테일 업스케일러.", description: "저화질 이미지를 상상력을 더해 초고화질로 변환해줍니다.", releaseDate: "2023.12", website: "https://magnific.ai", pricing: "Paid", tags: ["Upscale", "Detail"], thumbnail: "https://logo.clearbit.com/magnific.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-09", name: "Playground AI", category: "image", summary: "사용하기 쉬운 웹 생성기.", description: "필터 기능이 강력하고 커뮤니티 기능이 잘 되어 있습니다.", releaseDate: "2022.10", website: "https://playgroundai.com", pricing: "Free / Paid", tags: ["Web-based", "Filters"], thumbnail: "https://logo.clearbit.com/playground.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "img-10", name: "Recraft", category: "image", summary: "벡터 이미지 생성 특화.", description: "SVG 포맷으로 저장 가능한 벡터 그래픽과 아이콘을 생성합니다.", releaseDate: "2023.05", website: "https://recraft.ai", pricing: "Free / Paid", tags: ["Vector", "Icon"], thumbnail: "https://logo.clearbit.com/recraft.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 3. Video (영상 생성)
  {
    id: "vid-01", name: "Runway", category: "video",
    summary: "영상 생성 AI의 선두주자.",
    description: "텍스트 투 비디오, 모션 브러쉬 등 다양한 제어 기능을 제공합니다.",
    releaseDate: "2023.06", website: "https://runwayml.com", pricing: "Free Trial / Paid", tags: ["Gen-2", "Motion Brush"],
    thumbnail: "https://logo.clearbit.com/runwayml.com",
    rating: 0, ratingCount: 0, userRatings: [], comments: []
  },
  { id: "vid-02", name: "Pika", category: "video", summary: "애니메이션에 강한 생성기.", description: "사용하기 쉽고 특히 애니메이션 스타일 영상 생성에 강점이 있습니다.", releaseDate: "2023.12", website: "https://pika.art", pricing: "Free / Paid", tags: ["Animation", "Easy"], thumbnail: "https://logo.clearbit.com/pika.art", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-03", name: "Sora", category: "video", summary: "OpenAI의 혁명적 비디오 모델.", description: "최대 1분 길이의 고해상도 영상을 물리 법칙에 맞게 생성합니다. (현재 제한적 공개)", releaseDate: "2024.02", website: "https://openai.com/sora", pricing: "Unreleased", tags: ["Realistic", "OpenAI"], thumbnail: "https://logo.clearbit.com/openai.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  // 👇 [추가] Hailuo AI
  { 
    id: "vid-11", name: "Hailuo AI", category: "video",
    summary: "MiniMax의 고성능 비디오 생성 AI.",
    description: "텍스트를 고품질의 비디오로 변환해주는 MiniMax사의 최신 비디오 생성 모델입니다. 자연스러운 움직임이 특징입니다.",
    releaseDate: "2024.09", website: "https://hailuoai.com", pricing: "Free / Paid", 
    tags: ["Video", "MiniMax", "High Quality"], 
    thumbnail: "https://logo.clearbit.com/hailuoai.com", 
    rating: 0, ratingCount: 0, priceType: "부분 유료", userRatings: [], comments: [] 
  },
  { id: "vid-04", name: "Luma Dream Machine", category: "video", summary: "고퀄리티 무료 영상 생성.", description: "빠른 생성 속도와 높은 퀄리티를 무료로 체험할 수 있습니다.", releaseDate: "2024.06", website: "https://lumalabs.ai", pricing: "Free / Paid", tags: ["High Quality", "Fast"], thumbnail: "https://logo.clearbit.com/lumalabs.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-05", name: "Kling", category: "video", summary: "중국의 고성능 비디오 모델.", description: "Sora에 버금가는 긴 영상 생성 능력과 자연스러운 움직임을 보여줍니다.", releaseDate: "2024.06", website: "https://kling.kuaishou.com", pricing: "Free / Paid", tags: ["Long Video", "Realistic"], thumbnail: "https://logo.clearbit.com/kuaishou.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-06", name: "HeyGen", category: "video", summary: "AI 아바타 영상 제작.", description: "텍스트만 입력하면 실제 사람이 말하는 듯한 영상을 만들어줍니다.", releaseDate: "2022.09", website: "https://heygen.com", pricing: "Paid", tags: ["Avatar", "Marketing"], thumbnail: "https://logo.clearbit.com/heygen.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-07", name: "Synthesia", category: "video", summary: "기업 교육용 AI 아바타.", description: "다국어 지원 및 기업 교육, 프레젠테이션 영상 제작에 최적화되어 있습니다.", releaseDate: "2020.10", website: "https://synthesia.io", pricing: "Paid", tags: ["Business", "Avatar"], thumbnail: "https://logo.clearbit.com/synthesia.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-08", name: "Kaiber", category: "video", summary: "스타일리시한 영상 변환.", description: "기존 영상을 애니메이션이나 특정 스타일로 변환하는 데 특화되어 있습니다.", releaseDate: "2023.01", website: "https://kaiber.ai", pricing: "Paid", tags: ["Style Transfer", "Music Video"], thumbnail: "https://logo.clearbit.com/kaiber.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-09", name: "Leonardo Motion", category: "video", summary: "이미지를 영상으로.", description: "레오나르도 AI에서 생성한 이미지에 자연스러운 움직임을 부여합니다.", releaseDate: "2023.12", website: "https://leonardo.ai", pricing: "Credits", tags: ["Image-to-Video"], thumbnail: "https://logo.clearbit.com/leonardo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "vid-10", name: "Topaz Video AI", category: "video", summary: "AI 영상 업스케일링.", description: "저화질 영상을 고화질로 복원하고 프레임 속도를 부드럽게 만듭니다.", releaseDate: "2020.05", website: "https://topazlabs.com", pricing: "One-time Purchase", tags: ["Upscale", "Restoration"], thumbnail: "https://logo.clearbit.com/topazlabs.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 4. Voice (음성)
  { id: "voice-01", name: "ElevenLabs", category: "voice", summary: "가장 자연스러운 TTS.", description: "감정 표현이 가능한 최고의 텍스트 음성 변환 AI입니다.", releaseDate: "2023.01", website: "https://elevenlabs.io", pricing: "Free / Paid", tags: ["TTS", "Voice Cloning"], thumbnail: "https://logo.clearbit.com/elevenlabs.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-02", name: "Suno", category: "voice", summary: "AI 작곡 혁명.", description: "가사와 스타일만 입력하면 노래를 작곡하고 불러줍니다.", releaseDate: "2023.12", website: "https://suno.com", pricing: "Free / Paid", tags: ["Music", "Song"], thumbnail: "https://logo.clearbit.com/suno.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-03", name: "Udio", category: "voice", summary: "고음질 음악 생성.", description: "음질이 뛰어나고 음악적 구조가 탄탄한 노래를 생성합니다.", releaseDate: "2024.04", website: "https://udio.com", pricing: "Free / Paid", tags: ["High Fidelity", "Music"], thumbnail: "https://logo.clearbit.com/udio.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-04", name: "Murf AI", category: "voice", summary: "스튜디오 품질의 AI 보이스오버.", description: "영상 내레이션 및 프레젠테이션용 보이스 생성.", website: "https://murf.ai", releaseDate: "2020.10", pricing: "Free / Paid", tags: ["Voiceover", "Studio"], thumbnail: "https://logo.clearbit.com/murf.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-05", name: "PlayHT", category: "voice", summary: "초현실적인 AI 음성 생성기.", description: "팟캐스트 및 오디오북 제작에 최적화되어 있습니다.", website: "https://play.ht", releaseDate: "2020.08", pricing: "Free / Paid", tags: ["Podcast", "Ultra Realistic"], thumbnail: "https://logo.clearbit.com/play.ht", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-06", name: "Lovo", category: "voice", summary: "감정 표현이 풍부한 AI 성우.", description: "다양한 감정과 스타일의 목소리를 제공합니다.", website: "https://lovo.ai", releaseDate: "2019.11", pricing: "Free / Paid", tags: ["Genny", "Emotion"], thumbnail: "https://logo.clearbit.com/lovo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-07", name: "Speechify", category: "voice", summary: "텍스트를 오디오로 읽어주는 도구.", description: "문서, 웹페이지를 듣기 편한 음성으로 변환합니다.", website: "https://speechify.com", releaseDate: "2017.01", pricing: "Free / Paid", tags: ["Productivity", "Reading"], thumbnail: "https://logo.clearbit.com/speechify.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-08", name: "Voiser", category: "voice", summary: "한국어 특화 AI 성우 서비스.", description: "자연스러운 한국어 발음과 다양한 캐릭터 보이스.", website: "https://voiser.co.kr", releaseDate: "2021.03", pricing: "Free / Paid", tags: ["Korean", "Voice Actor"], thumbnail: "https://logo.clearbit.com/voiser.co.kr", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-09", name: "Resemble AI", category: "voice", summary: "실시간 음성 변조 및 클로닝.", description: "게임 및 보안용 음성 복제 기술.", website: "https://resemble.ai", releaseDate: "2019.02", pricing: "Paid", tags: ["Cloning", "Security"], thumbnail: "https://logo.clearbit.com/resemble.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "voice-10", name: "Descript", category: "voice", summary: "오디오 편집을 문서 편집처럼.", description: "텍스트를 수정하면 오디오도 수정되는 편집 툴.", website: "https://descript.com", releaseDate: "2017.12", pricing: "Free / Paid", tags: ["Editing", "Podcast"], thumbnail: "https://logo.clearbit.com/descript.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 5. Automation (자동화)
  { id: "auto-01", name: "n8n", category: "automation", summary: "워크플로우 자동화 오픈소스 툴.", description: "복잡한 업무 자동화도 노코드로 해결.", website: "https://n8n.io", releaseDate: "2019.10", pricing: "Free / Enterprise", tags: ["Workflow", "No-code"], thumbnail: "https://logo.clearbit.com/n8n.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-02", name: "Make", category: "automation", summary: "시각적 자동화 도구.", description: "직관적인 비주얼 오토메이션 플랫폼.", website: "https://make.com", releaseDate: "2016", pricing: "Free / Paid", tags: ["Workflow", "Integration"], thumbnail: "https://logo.clearbit.com/make.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-03", name: "Zapier", category: "automation", summary: "가장 많은 앱을 연동하는 자동화.", description: "5000개 이상의 앱을 손쉽게 연결.", website: "https://zapier.com", releaseDate: "2011.08", pricing: "Free / Paid", tags: ["Integration", "Easy"], thumbnail: "https://logo.clearbit.com/zapier.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-04", name: "Bardeen", category: "automation", summary: "브라우저 기반 AI 자동화.", description: "웹 브라우저에서 반복 작업을 대신해주는 AI.", website: "https://bardeen.ai", releaseDate: "2020.05", pricing: "Free / Paid", tags: ["Browser", "Scraping"], thumbnail: "https://logo.clearbit.com/bardeen.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-05", name: "UiPath", category: "automation", summary: "엔터프라이즈급 RPA 플랫폼.", description: "대규모 기업 업무 자동화의 표준.", website: "https://uipath.com", releaseDate: "2005", pricing: "Enterprise", tags: ["RPA", "Enterprise"], thumbnail: "https://logo.clearbit.com/uipath.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-06", name: "Power Automate", category: "automation", summary: "Microsoft 생태계 자동화.", description: "윈도우 및 오피스 앱과의 완벽한 연동.", website: "https://powerautomate.microsoft.com", releaseDate: "2016.10", pricing: "Paid", tags: ["Microsoft", "Desktop"], thumbnail: "https://logo.clearbit.com/microsoft.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-07", name: "IFTTT", category: "automation", summary: "간단한 조건문 자동화.", description: "일상 생활 자동화에 최적화된 서비스.", website: "https://ifttt.com", releaseDate: "2010.12", pricing: "Free / Paid", tags: ["IoT", "Personal"], thumbnail: "https://logo.clearbit.com/ifttt.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-08", name: "Workato", category: "automation", summary: "비즈니스 프로세스 통합.", description: "IT와 비즈니스 팀을 위한 강력한 통합 툴.", website: "https://workato.com", releaseDate: "2013", pricing: "Enterprise", tags: ["Integration", "Business"], thumbnail: "https://logo.clearbit.com/workato.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-09", name: "Tray.io", category: "automation", summary: "로우코드 자동화 플랫폼.", description: "유연하고 확장성 높은 워크플로우 구축.", website: "https://tray.io", releaseDate: "2012", pricing: "Paid", tags: ["Low-code", "API"], thumbnail: "https://logo.clearbit.com/tray.io", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "auto-10", name: "Relay.app", category: "automation", summary: "사람 개입 워크플로우 자동화.", description: "AI와 사람이 협업하는 자동화 프로세스.", website: "https://relay.app", releaseDate: "2023", pricing: "Free / Paid", tags: ["Collaboration", "Human-in-the-loop"], thumbnail: "https://logo.clearbit.com/relay.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] },

  // 6. Search (검색)
  { id: "search-01", name: "Perplexity", category: "search", summary: "출처 제공 AI 검색.", description: "신뢰할 수 있는 대화형 검색 엔진.", website: "https://perplexity.ai", releaseDate: "2022.08", pricing: "Free / $20", tags: ["Search", "Citations"], thumbnail: "https://logo.clearbit.com/perplexity.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-02", name: "Genspark", category: "search", summary: "목적 맞춤형 AI 검색 에이전트.", description: "특화된 스파크페이지를 생성하는 검색 AI.", website: "https://genspark.ai", releaseDate: "2024", pricing: "Free", tags: ["Agent", "Visual"], thumbnail: "https://logo.clearbit.com/genspark.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-03", name: "You.com", category: "search", summary: "개인화된 AI 검색 어시스턴트.", description: "다양한 모드를 제공하는 사생활 보호 검색.", website: "https://you.com", releaseDate: "2021.11", pricing: "Free / Paid", tags: ["Private", "Assistant"], thumbnail: "https://logo.clearbit.com/you.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-04", name: "Bing Chat", category: "search", summary: "GPT-4 기반 마이크로소프트 검색.", description: "웹 검색과 결합된 강력한 생성형 답변.", website: "https://bing.com/chat", releaseDate: "2023.02", pricing: "Free", tags: ["Microsoft", "GPT-4"], thumbnail: "https://logo.clearbit.com/bing.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-05", name: "Arc Search", category: "search", summary: "브라우저가 대신 검색.", description: "여러 페이지를 읽고 요약해주는 모바일 검색.", website: "https://arc.net", releaseDate: "2024.01", pricing: "Free", tags: ["Browser", "Summary"], thumbnail: "https://logo.clearbit.com/arc.net", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-06", name: "Komo", category: "search", summary: "광고 없는 빠르고 정확한 AI 검색.", description: "커뮤니티 중심의 인사이트 검색.", website: "https://komo.ai", releaseDate: "2022", pricing: "Free", tags: ["Ad-free", "Fast"], thumbnail: "https://logo.clearbit.com/komo.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-07", name: "Phind", category: "search", summary: "개발자를 위한 AI 검색.", description: "코딩 질문에 최적화된 답변 제공.", website: "https://phind.com", releaseDate: "2023", pricing: "Free / Paid", tags: ["Developer", "Coding"], thumbnail: "https://logo.clearbit.com/phind.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-08", name: "Andi", category: "search", summary: "친근한 대화형 검색 챗봇.", description: "광고 없이 정보를 요약해주는 검색 친구.", website: "https://andisearch.com", releaseDate: "2022", pricing: "Free", tags: ["Chat", "Visual"], thumbnail: "https://logo.clearbit.com/andisearch.com", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-09", name: "Metaphor", category: "search", summary: "LLM을 위해 설계된 검색 API.", description: "AI가 이해하기 쉬운 형태의 검색 결과.", website: "https://exa.ai", releaseDate: "2023", pricing: "API", tags: ["API", "LLM"], thumbnail: "https://logo.clearbit.com/exa.ai", rating: 0, ratingCount: 0, userRatings: [], comments: [] },
  { id: "search-10", name: "Consensus", category: "search", summary: "AI 기반 과학 논문 검색.", description: "연구 결과와 논문에서 신뢰할 수 있는 답변 추출.", website: "https://consensus.app", releaseDate: "2022", pricing: "Free / Paid", tags: ["Academic", "Science"], thumbnail: "https://logo.clearbit.com/consensus.app", rating: 0, ratingCount: 0, userRatings: [], comments: [] }
];