import FAQClient, { type FaqSection } from "@/app/faq/page.client";
import { enMetadata } from "../enMetadata";

export const metadata = enMetadata({
  title: "FAQ",
  description:
    "Frequently asked questions about illo — what the service is, accounts and membership, the community, AI tools, mini games and cotton candy points, projects and troubleshooting.",
  koPath: "/faq",
  enPath: "/en/faq",
  keywords: ["illo FAQ", "frequently asked questions", "illo help", "AI community FAQ"],
});

const sections: FaqSection[] = [
  {
    category: "About the service",
    items: [
      {
        q: "What is illo?",
        a: "illo is an AI community platform where you can enjoy AI tool information, insights, a community and mini games all in one place. Keep up with the latest AI trends, compare hundreds of AI tools by category, and talk freely with people who share your interests.",
      },
      {
        q: "Is illo free?",
        a: "Yes — all core services are 100% free. Searching AI tools, reading insight articles, taking part in the community and playing mini games are all available at no cost.",
      },
      {
        q: "What services do you offer?",
        a: "We currently offer the following.\n\n• AI Tools — search, compare and review AI services by category (200+)\n• Insights — AI trend, guide, analysis, report and curation articles\n• Community — a feed-style board with information sharing and emoji reactions\n• Mini games — 17 browser games, a hall of fame (rankings) and cotton candy rewards\n• Projects — programs illo is building (Workillo, Monglo, Family Records), coming soon\n• Suggestions — feedback on how to improve the service (linked at the bottom of each page)",
      },
      {
        q: "How was illo built?",
        a: "illo is built and operated using a 'vibe coding' approach, working alongside AI. Some insight content is generated by an automated system (n8n + AI) that collects and analyzes global AI news, and we do not hide the fact that we use AI.",
      },
      {
        q: "Can I use illo on mobile?",
        a: "Yes — every page is optimized for mobile. You can use it directly in a mobile browser without installing an app, and the bottom tab bar lets you jump quickly to the main menus.",
      },
    ],
  },
  {
    category: "Account & membership",
    items: [
      {
        q: "How do I sign up?",
        a: "Tap the 'Log in' button at the top right (top or bottom on mobile), then use the 'Sign up' tab to register quickly with your email. Google sign-in is also supported.",
      },
      {
        q: "Can I use the service without an account?",
        a: "Yes — most content (AI tool search, insight articles, mini games) is available without logging in. However, personalized features such as posting and commenting in the community, earning cotton candy and daily check-ins require an account.",
      },
      {
        q: "I can't log in.",
        a: "Please check the following in order.\n\n• Whether your email and password were entered correctly\n• Whether your browser is set to block cookies or local storage\n• Some login features may be limited in private/incognito mode\n\nIf that does not resolve it, let us know via Suggestions or at illo@illo.im.",
      },
      {
        q: "How do I change my nickname?",
        a: "After logging in, go to My Page > Edit Profile to change your nickname. The new nickname will appear on your community posts and comments.",
      },
      {
        q: "How do I delete my account?",
        a: "You can withdraw your membership from My Page. Your account information is deleted immediately on withdrawal, and posts you created are deleted on request.",
      },
    ],
  },
  {
    category: "Community",
    items: [
      {
        q: "Can I post in the community?",
        a: "Yes! After logging in, use the 'Write' button at the bottom right of the community to post freely. Share AI tips, questions, wins, small talk — there is no topic restriction.",
      },
      {
        q: "What are the reactions (like, cheer, insight, laugh)?",
        a: "They are the range of reactions you can leave on a post. Beyond a simple like, you can express yourself with 'Cheering 👏', 'Helpful 💡', 'Funny 😂' and more. You can leave one reaction per post, and pressing it again cancels it.",
      },
      {
        q: "How do topic tags work?",
        a: "If you pick a topic tag when writing a post, the topic filter at the top of the community lets readers see only posts on that topic — making it easier to read just what interests you.",
      },
      {
        q: "Can I post something written with AI?",
        a: "Yes, you can. Please just indicate whether the post was 'AI-assisted' or 'AI-generated' when you write it. illo aims for a culture of being transparent about AI use.",
      },
      {
        q: "What should I do if I find an inappropriate post?",
        a: "Please report it through Suggestions (linked at the bottom of the page) using the 'Bug report' or 'Other' category. We will review and act quickly.",
      },
    ],
  },
  {
    category: "AI tools",
    items: [
      {
        q: "How is the AI tool information collected?",
        a: "illo researches tools directly and keeps information up to date through user tips and official sources. For each category we highlight the five most widely used tools as a TOP 5.",
      },
      {
        q: "What is the difference between the 'API' and 'Visit site' buttons?",
        a: "• Visit site — goes to the official website of that AI tool.\n• API — goes to the official API docs or console so developers can integrate right away. (Shown only for tools that offer an API.)",
      },
      {
        q: "How are the tool rankings decided?",
        a: "We rank tools within each category based on a combination of usage frequency, recognition, user ratings and feature completeness. User ratings and reviews are also factored in for greater accuracy.",
      },
      {
        q: "I'd like to suggest a new AI tool.",
        a: "Please submit the name and link of the tool through Suggestions using the 'Feature request' category. We will review it and add it.",
      },
    ],
  },
  {
    category: "Mini games & cotton candy",
    items: [
      {
        q: "What is cotton candy?",
        a: "Cotton candy (🍭) is the point currency used on illo. You can collect it through daily check-ins, completing missions and playing mini games, and it adds a layer of fun to various activities.",
      },
      {
        q: "How do I earn cotton candy?",
        a: "You can collect cotton candy in the following ways.\n\n• Daily check-in — +50 once a day (bonus +200 for a 7-day streak)\n• Playing mini games — +50 for playing Galaxy Merge, 2048 or Boss Clicker for at least one minute (once a day)\n• Reaching game goals — rewards for milestones such as reaching 2048 or defeating a boss\n• Missions and achievements — extra rewards for completing missions across the site",
      },
      {
        q: "Can I get the one-minute play reward for every game?",
        a: "The one-minute play reward (+50) is granted only once per day. Playing any one of Galaxy Merge, 2048 or Boss Clicker for at least a minute earns that day's reward. (Switching games still counts as one reward per day.)",
      },
      {
        q: "My cotton candy disappeared.",
        a: "Cotton candy is saved against your logged-in account. Anything earned while logged out is stored only in your browser data, so it can be lost if you clear your cache or switch devices. Play while logged in to keep it safe.",
      },
      {
        q: "What mini games are there?",
        a: "Galaxy Merge, 2048, Boss Clicker, Snake, Match-3 Puzzle, Slide Puzzle, Card Flip, AI Trivia Quiz, Typing Speed, Color Match, Roulette, Slot Machine and more — 17 browser games you can play instantly with no installation. Most games record your score in the hall of fame.",
      },
      {
        q: "How does the hall of fame (ranking) work?",
        a: "For most games, your score is submitted to the hall of fame at the end of a round and the TOP 5 is shown per game.\n\n• Only logged-in members have their scores recorded\n• Only your single best score is kept per game\n• For games where lower is better, such as puzzles and number guessing, lower scores rank higher",
      },
    ],
  },
  {
    category: "Projects",
    items: [
      {
        q: "What is the Projects page?",
        a: "It is where we introduce the programs illo is building. 'Workillo' can already be tried directly in your browser, while 'Monglo : Animal Encyclopedia' and 'Family Records' are in preparation. They are listed in the menu already, and the remaining detail pages will be published as they are finished.",
      },
      {
        q: "Can I leave feedback on a project?",
        a: "Yes! For now, please leave your opinions and requests about a program through Suggestions at the bottom of the page. After the official launch you will be able to leave feedback directly on each project page, and we will actively reflect it in development.",
      },
      {
        q: "When will the programs launch?",
        a: "Each program is at a different stage. 'Workillo' can already be tried on the web for free (50 free runs per day when logged in). The others are in planning and development, and launch news will be announced through Notices.",
      },
    ],
  },
  {
    category: "Technical & other",
    items: [
      {
        q: "Where is my data stored?",
        a: "Account data for logged-in users (cotton candy, profile and so on) is stored on secure servers. Some records created while logged out (such as temporary scores) are stored in your browser's localStorage and may be deleted along with your browser data.",
      },
      {
        q: "The site looks broken or is slow. (Bug)",
        a: "First, update your browser to the latest version and clear the cache (Ctrl+Shift+R or Cmd+Shift+R). If the problem persists, report it through Suggestions as a 'Bug report' with your browser, operating system and a screenshot, and we will look into it quickly.",
      },
      {
        q: "Is there a dark mode?",
        a: "Yes — use the display mode toggle in the header or the More menu to switch between light and dark mode. Your choice is remembered on your next visit.",
      },
      {
        q: "Is illo open source?",
        a: "illo is not an open-source project at the moment, but we plan to release some components and tools as open source in the future.",
      },
      {
        q: "Where can I send an inquiry?",
        a: "Use the Suggestions link at the bottom of the page, or email illo@illo.im. We will reply as soon as we can.",
      },
    ],
  },
];

export default function EnFAQPage() {
  return (
    <FAQClient
      sections={sections}
      label="FAQ"
      title="Frequently asked questions"
      subtitle="Have a question? Find your answer below."
      ctaHint="Didn't find the answer you were looking for?"
      ctaLabel="Leave a suggestion →"
      ctaHref="/suggestion"
    />
  );
}
