import { NextResponse } from "next/server";

const seedPosts = [
  {
    id: "seed-1",
    author: "DORI 운영팀",
    avatar: "🤖",
    title: "DORI-AI에 오신 것을 환영합니다! 🎉",
    content:
      "안녕하세요! DORI-AI 커뮤니티에 오신 여러분을 환영합니다. 이곳은 AI에 관심 있는 모든 분들이 자유롭게 정보를 나누는 공간입니다. 매일 새로운 AI 트렌드 기사가 올라오고, 미니게임으로 솜사탕 포인트도 모을 수 있어요!",
    tags: ["공지"],
    likes: 47,
    sparks: 47,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-01T09:00:00.000Z",
    date: "2026-03-01",
    views: 312,
  },
  {
    id: "seed-2",
    author: "AI탐험가",
    avatar: "🚀",
    title: "ChatGPT 프롬프트 꿀팁 모음 📝",
    content:
      "ChatGPT를 제대로 활용하려면 프롬프트가 중요해요. 제가 써본 꿀팁들을 공유할게요.\n\n1. 역할 부여하기: '당신은 10년 경력의 마케터입니다'처럼 역할을 주면 훨씬 전문적인 답변이 나와요.\n2. 단계별로 요청하기: 한 번에 다 물어보는 것보다 단계적으로 질문하면 더 정확해요.\n3. 예시 제공하기: '이런 형식으로 써줘'라고 예시를 보여주면 원하는 결과가 나옵니다.",
    tags: ["정보공유", "ChatGPT"],
    likes: 38,
    sparks: 38,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-02T10:30:00.000Z",
    date: "2026-03-02",
    views: 256,
  },
  {
    id: "seed-3",
    author: "테크뉴스",
    avatar: "📰",
    title: "2026년 AI 트렌드 총정리 🤖",
    content:
      "올해 AI 분야에서 가장 핫한 키워드들을 정리해봤습니다.\n\n✅ AI 에이전트의 부상 - NVIDIA GTC 2026에서 발표된 Agent Toolkit이 핵심\n✅ 멀티모달 AI - 텍스트, 이미지, 영상을 동시에 처리\n✅ AI 코딩 어시스턴트 - 개발자 생산성 혁명\n✅ 소형 언어 모델 - 엣지 디바이스에서 실행 가능한 경량 AI\n\n여러분은 어떤 트렌드가 가장 기대되시나요?",
    tags: ["뉴스", "AI"],
    likes: 29,
    sparks: 29,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-03T08:00:00.000Z",
    date: "2026-03-03",
    views: 198,
  },
  {
    id: "seed-4",
    author: "게임매니아",
    avatar: "🎮",
    title: "던전RPG 공략법 알려드립니다! ⚔️",
    content:
      "DORI-AI 던전RPG 게임 하다가 막히신 분들을 위한 팁!\n\n초반에는 마법사 클래스가 제일 강해요. MP 관리만 잘 하면 보스도 어렵지 않습니다.\n\n아이템 조합 팁:\n- 검 + 방패 = 전사 빌드 (안정적)\n- 지팡이 + 책 = 마법사 빌드 (고화력)\n\n솜사탕 포인트도 게임하면 모을 수 있으니 꼭 해보세요!",
    tags: ["미니게임", "공략"],
    likes: 24,
    sparks: 24,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-04T14:00:00.000Z",
    date: "2026-03-04",
    views: 187,
  },
  {
    id: "seed-5",
    author: "솜사탕부자",
    avatar: "🍭",
    title: "솜사탕 포인트 빠르게 모으는 방법 🍭",
    content:
      "DORI-AI 솜사탕 포인트 효율적으로 모으는 방법 공유해요!\n\n📌 매일 하면 좋은 것들:\n- 출석 체크: 50 솜사탕 (무조건!)\n- 트렌드 기사 읽기: 30 솜사탕\n- 퀴즈 풀기: 50 솜사탕\n- 미니게임 1판: 40 솜사탕\n\n7일 연속 출석하면 보너스 200개도 받을 수 있어요. 저는 이 방법으로 일주일 만에 1000개 모았습니다!",
    tags: ["포인트팁", "솜사탕"],
    likes: 52,
    sparks: 52,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-05T11:00:00.000Z",
    date: "2026-03-05",
    views: 341,
  },
  {
    id: "seed-6",
    author: "AI초보자",
    avatar: "🌱",
    title: "AI 공부 어디서부터 시작해야 할까요? 🤔",
    content:
      "AI에 관심이 생겼는데 뭐부터 공부해야 할지 막막해요. 비전공자인데 AI를 업무에 활용하고 싶습니다. 추천해주실 자료나 순서가 있을까요?",
    tags: ["질문", "입문"],
    likes: 15,
    sparks: 15,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-06T16:00:00.000Z",
    date: "2026-03-06",
    views: 142,
  },
  {
    id: "seed-7",
    author: "DORI 운영팀",
    avatar: "🤖",
    title: "신규 기능 업데이트 안내 ✨",
    content:
      "DORI-AI가 새로워졌습니다!\n\n🆕 새로운 기능들:\n- 솜사탕 포인트 시스템 강화\n- 매일 자동 AI 트렌드 기사 2개 업데이트\n- 미니게임 23종 추가\n- 포인트 상점 오픈 예정\n\n앞으로도 더 좋은 서비스로 찾아뵙겠습니다. 많은 이용 부탁드려요!",
    tags: ["공지", "업데이트"],
    likes: 33,
    sparks: 33,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-07T09:00:00.000Z",
    date: "2026-03-07",
    views: 228,
  },
  {
    id: "seed-8",
    author: "개발자K",
    avatar: "💻",
    title: "n8n으로 AI 자동화 워크플로우 만들기 🔧",
    content:
      "n8n을 이용해서 ChatGPT API와 노션을 연동하는 자동화를 구축했어요.\n\n기본 흐름:\n웹훅 수신 → ChatGPT 요약 → 노션 페이지 생성 → 슬랙 알림\n\n이 워크플로우로 하루에 2시간 이상 절약하고 있습니다. 관심 있으신 분은 댓글 달아주세요!",
    tags: ["개발", "자동화"],
    likes: 41,
    sparks: 41,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-08T13:00:00.000Z",
    date: "2026-03-08",
    views: 267,
  },
  {
    id: "seed-9",
    author: "트렌드헌터",
    avatar: "🎯",
    title: "OpenAI Sora 종료... AI 영상 시장 어디로? 📹",
    content:
      "어제 OpenAI가 Sora를 전격 종료한다고 발표했죠. 디즈니와 1조원대 파트너십도 날아갔는데요.\n\n개인적으로는 Runway나 Kling 같은 전문 서비스들이 반사이익을 얻을 것 같아요.\n\n여러분은 AI 영상 생성 서비스 중 어떤 걸 쓰고 계신가요?",
    tags: ["뉴스", "OpenAI"],
    likes: 27,
    sparks: 27,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-09T10:00:00.000Z",
    date: "2026-03-09",
    views: 189,
  },
  {
    id: "seed-10",
    author: "퀴즈왕",
    avatar: "🧠",
    title: "AI 상식 퀴즈 - 맞춰보세요! 🧠",
    content:
      "간단한 AI 상식 퀴즈 내볼게요!\n\nQ1. GPT의 풀네임은?\nQ2. 이미지 생성 AI 중 가장 유명한 것은?\nQ3. AI가 체스 세계 챔피언을 처음 이긴 해는?\n\n댓글로 답 달아주세요~ 정답자에게는... 응원의 박수를! 👏",
    tags: ["퀴즈", "AI상식"],
    likes: 19,
    sparks: 19,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-10T15:00:00.000Z",
    date: "2026-03-10",
    views: 156,
  },
  {
    id: "seed-11",
    author: "마케터L",
    avatar: "📊",
    title: "AI로 마케팅 콘텐츠 만드는 법 📊",
    content:
      "마케팅 업무에 AI를 도입하고 나서 생산성이 3배 올랐어요.\n\n주로 사용하는 것들:\n1. ChatGPT - 카피라이팅, 이메일 초안\n2. Midjourney - 배너 이미지 제작\n3. Gamma - 프레젠테이션 자동 생성\n\n특히 SNS 콘텐츠 캘린더를 AI로 만들면 한 달치를 하루에 끝낼 수 있어요!",
    tags: ["마케팅", "AI활용"],
    likes: 36,
    sparks: 36,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-11T11:00:00.000Z",
    date: "2026-03-11",
    views: 243,
  },
  {
    id: "seed-12",
    author: "영상편집자",
    avatar: "🎬",
    title: "AI 영상 편집 도구 솔직 후기 🎬",
    content:
      "영상 편집에 AI를 써본 솔직한 후기를 공유합니다.\n\n⭐ Runway Gen-3: 퀄리티 최고, 근데 비쌈\n⭐ CapCut AI: 무료 기능 많고 직관적\n⭐ Descript: 텍스트로 영상 편집 가능, 신기함\n\n유튜브 쇼츠 만들 때는 CapCut이 제일 편하더라고요. 여러분은 어떤 도구 쓰세요?",
    tags: ["영상", "AI도구"],
    likes: 22,
    sparks: 22,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-12T14:00:00.000Z",
    date: "2026-03-12",
    views: 178,
  },
  {
    id: "seed-13",
    author: "학생J",
    avatar: "📚",
    title: "ChatGPT로 공부하는 나만의 방법 📚",
    content:
      "수험생인데 ChatGPT를 공부에 활용하는 방법을 공유할게요.\n\n1. 개념 설명 요청: '중학생도 이해할 수 있게 설명해줘'\n2. 문제 만들어달라고 하기: '이 개념으로 연습문제 5개 만들어줘'\n3. 오답 분석: '내가 틀린 이유를 설명해줘'\n\n주의할 점은 틀린 정보도 자신 있게 말하니까 꼭 교과서랑 대조하세요!",
    tags: ["학습", "ChatGPT"],
    likes: 31,
    sparks: 31,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-13T09:00:00.000Z",
    date: "2026-03-13",
    views: 214,
  },
  {
    id: "seed-14",
    author: "창업가M",
    avatar: "💡",
    title: "AI 스타트업 아이디어 브레인스토밍 💡",
    content:
      "요즘 AI 창업 아이디어 모으고 있는데 같이 브레인스토밍 해봐요!\n\n제가 생각해둔 것들:\n- AI 개인 영양사 (식단 사진 찍으면 분석)\n- AI 법률 서류 초안 작성 서비스\n- AI 면접 코치\n\n여러분이 생각하는 AI 창업 아이디어는 뭔가요?",
    tags: ["창업", "AI비즈니스"],
    likes: 44,
    sparks: 44,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-14T12:00:00.000Z",
    date: "2026-03-14",
    views: 298,
  },
  {
    id: "seed-15",
    author: "디자이너P",
    avatar: "🎨",
    title: "Midjourney v7 리뷰 - 진짜 놀랍습니다 🎨",
    content:
      "Midjourney v7을 써봤는데 진짜 퀄리티가 미쳤어요.\n\n특히 좋아진 점:\n- 인체 비율이 훨씬 자연스러워짐\n- 텍스트 렌더링 개선됨\n- 스타일 일관성 유지가 잘 됨\n\n단점은 여전히 손가락이 가끔 이상하게 나오는 것... 근데 그것도 많이 개선됐어요!",
    tags: ["디자인", "Midjourney"],
    likes: 28,
    sparks: 28,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-15T16:00:00.000Z",
    date: "2026-03-15",
    views: 192,
  },
  {
    id: "seed-16",
    author: "번역가Q",
    avatar: "🌍",
    title: "AI 번역 도구 비교 - 어떤 게 제일 잘 될까? 🌍",
    content:
      "번역 업무에 AI를 써보면서 비교한 결과를 공유해요.\n\n🥇 DeepL: 자연스러운 번역, 특히 유럽어\n🥈 ChatGPT: 컨텍스트 이해 최고, 뉘앙스 살림\n🥉 Google 번역: 빠르고 무료, 기본기 충실\n\n전문 번역 작업엔 DeepL + ChatGPT 검수 조합이 최고예요!",
    tags: ["번역", "언어AI"],
    likes: 17,
    sparks: 17,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-17T10:00:00.000Z",
    date: "2026-03-17",
    views: 134,
  },
  {
    id: "seed-17",
    author: "부업러R",
    avatar: "💰",
    title: "AI로 월 100만원 부업하는 방법 💰",
    content:
      "AI 도구를 활용한 부업으로 지난달 120만원 벌었어요!\n\n제가 하는 것들:\n1. AI 블로그 운영 (애드센스)\n2. 미드저니로 스톡 이미지 판매\n3. ChatGPT로 전자책 제작 판매\n\n처음 3개월은 수익이 별로였는데 꾸준히 하다 보니 늘더라고요. 질문 있으시면 댓글로!",
    tags: ["부업", "AI수익"],
    likes: 67,
    sparks: 67,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-19T13:00:00.000Z",
    date: "2026-03-19",
    views: 432,
  },
  {
    id: "seed-18",
    author: "보안전문가S",
    avatar: "🛡️",
    title: "AI 시대의 사이버 보안 위협 ⚠️",
    content:
      "AI가 발전하면서 사이버 보안 위협도 진화하고 있어요.\n\n최근 주목할 위협들:\n- AI 딥페이크를 이용한 사기\n- AI가 생성한 피싱 이메일 (문법 오류 없어서 더 위험)\n- 자동화된 해킹 시도 증가\n\n대응 방법: 2단계 인증 필수, 의심스러운 연락은 별도 채널로 확인!",
    tags: ["보안", "AI위협"],
    likes: 25,
    sparks: 25,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-21T09:00:00.000Z",
    date: "2026-03-21",
    views: 201,
  },
  {
    id: "seed-19",
    author: "육아맘T",
    avatar: "👶",
    title: "아이 교육에 AI 활용하기 👶",
    content:
      "초등학생 아이를 키우면서 AI 교육 도구를 써본 경험을 나눠요.\n\n좋았던 것들:\n- Khan Academy Khanmigo: AI 과외 선생님\n- Scratch + AI 블록: 코딩 학습\n- 그림 그리기 AI: 창의력 자극\n\n주의할 점은 AI 답변을 그대로 믿지 않도록 비판적 사고를 함께 가르치는 게 중요해요!",
    tags: ["교육", "키즈AI"],
    likes: 21,
    sparks: 21,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-23T11:00:00.000Z",
    date: "2026-03-23",
    views: 167,
  },
  {
    id: "seed-20",
    author: "DORI 운영팀",
    avatar: "🎁",
    title: "🎁 커뮤니티 첫 댓글 이벤트 - 솜사탕 500개!",
    content:
      "커뮤니티 오픈 기념 이벤트를 진행합니다!\n\n참여 방법:\n1. 이 게시글에 자기소개 댓글 달기\n2. 어떤 AI 도구를 주로 사용하는지 공유하기\n\n참여자 전원에게 솜사탕 500개를 지급합니다! (마이페이지에서 확인)\n\n이벤트 기간: 상시 진행\n\n많은 참여 부탁드려요! 🙏",
    tags: ["이벤트"],
    likes: 89,
    sparks: 89,
    comments: 0,
    commentsList: [],
    createdAt: "2026-03-25T10:00:00.000Z",
    date: "2026-03-25",
    views: 567,
  },
];

export async function GET() {
  return NextResponse.json({ posts: seedPosts });
}
